import type { Question } from "../../../types";

// FAA ATP written-test question bank, batch 9.
// Source: Prepware "Study Session Results" printout, source questions 630-687
// (PDF pages 121-135 of 258).
// This page range continues to be dominated by performance-chart, flight-log,
// and EPR/N1-chart reading questions that depend on figures not included in
// the source PDF (including a run of "dump time" problems tied to Figure 70's
// dump-rate chart). Skipped original source numbers: 630, 631, 632, 633, 634,
// 635, 637, 640, 641, 644, 645, 646, 647, 650, 651, 652, 653, 654, 655, 656,
// 659, 660, 662, 664, 666, 671, 672, 674, 675, 676, 677, 680, 681, 683, 685,
// 686, and 687.
export const FAA_ATP_BATCH_09_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "Which maximum range factor decreases as weight decreases?",
    options: ["Angle of attack.", "Altitude.", "Airspeed."],
    answer: 2,
    explain:
      "As fuel is consumed and the airplane's weight decreases, the optimum airspeed and power setting may decrease, or the optimum altitude may increase. The optimum angle of attack does not change with changes in weight. Answer (A) is incorrect because the factors of maximum range are weight, altitude, and aerodynamic configuration of the airplane, not angle of attack. Answer (B) is incorrect because maximum range altitude may increase with a decrease in weight.",
    reference: "FAA Airplane Flying Handbook - Range Performance",
  },
  {
    id: 2,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "Which term describes the hydroplaning which occurs when an airplane's tire is effectively held off a smooth runway surface by steam generated by friction?",
    options: ["Reverted rubber hydroplaning.", "Dynamic hydroplaning.", "Viscous hydroplaning."],
    answer: 0,
    explain:
      "This would typically occur if excessive braking kept a wheel from rotating. Answer (B) is incorrect because dynamic hydroplaning occurs when there is standing water or slush on the runway which forms a wedge that lifts the tire away from contact with the runway surface. Answer (C) is incorrect because viscous hydroplaning occurs on a thin film of water on a smooth (e.g., painted or rubber-coated) runway surface.",
    reference: "FAA Airplane Flying Handbook - Hydroplaning",
  },
  {
    id: 3,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "At what speed, with reference to L/D(MAX), does maximum range for a jet airplane occur?",
    options: ["A speed less than that for L/D(MAX).", "A speed equal to that for L/D(MAX).", "A speed greater than that for L/D(MAX)."],
    answer: 2,
    explain:
      "Maximum range is obtained at the aerodynamic condition which produces a maximum proportion between the square root of the lift coefficient and the drag coefficient. It occurs where the proportion between velocity and thrust required is greatest. This point is located by a straight line from the origin tangent to the curve, and is consequently at a higher airspeed than L/D(MAX). Answer (A) is incorrect because a speed greater than L/D(MAX) will obtain maximum range for a jet airplane. Answer (B) is incorrect because a speed equal to that of L/D(MAX) is a jet airplane's maximum endurance, not range.",
    reference: "FAA Airplane Flying Handbook - Range Performance",
  },
  {
    id: 4,
    subject: "FAA ATP",
    system: "Airport & Approach Operations",
    q: "Upon landing, thrust reversers",
    options: [
      "are required to obtain the calculated stopping distances.",
      "should be deployed as soon as the nose wheel is in firm contact with the runway.",
      "should be deployed immediately upon landing when airspeeds are highest.",
    ],
    answer: 1,
    explain:
      "If operating an aircraft such as the MD-80, thrust reversers should be deployed as soon as the nose wheel is in firm contact with the runway.",
    reference: "Aircraft Flight Manual - Landing Procedures",
  },
  {
    id: 5,
    subject: "FAA ATP",
    system: "Regulations & Certification",
    q: "A commercial operator plans to ferry a large, four-engine, reciprocating-engine-powered airplane from one facility to another to repair an inoperative engine. Which is an operational requirement for the three-engine flight?",
    options: [
      "The gross weight at takeoff may not exceed 75 percent of the maximum certificated gross weight.",
      "Weather conditions at the takeoff and destination airports must be VFR.",
      "The computed takeoff distance to reach V(1) must not exceed 70 percent of the effective runway length.",
    ],
    answer: 1,
    explain:
      "A commercial operator of large aircraft may conduct a ferry flight of a four-engine airplane or a turbine-engine-powered, three-engine airplane with one engine inoperative, to a base for the purpose of repairing the engine. Several restrictions apply to such flights. These include: 1. The Airplane Flight Manual must include procedures and performance data which allow for the safe operation of such a flight. 2. The initial climb cannot be over thickly-populated areas. 3. Weather conditions at the takeoff and destination airports must be VFR. 4. Only required flight crewmembers may be on board the aircraft.",
    reference: "14 CFR 121.197",
  },
  {
    id: 6,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "What recovery would be appropriate in the event of compressor stall?",
    options: [
      "Reduce the throttle and then rapidly advance the throttle to decrease the angle of attack on the compressor blades, creating more airflow.",
      "Reduce the throttle and then slowly advance the throttle again and decrease the aircraft's angle of attack.",
      "Advance the throttle slowly to increase airflow and decrease the angle of attack on one or more compressor blades.",
    ],
    answer: 1,
    explain:
      "If a compressor stall is transient and intermittent, the indication will be an intermittent 'bang' as backfire and flow reversal take place. If the stall develops and becomes steady, strong vibration and a loud roar develop from the continuous flow reversal. The possibility of damage is immediate from a steady stall. Recovery must be accomplished quickly by reducing throttle setting, lowering the airplane angle of attack, and increasing airspeed.",
    reference: "FAA Airplane Flying Handbook - Turbine Engines",
  },
  {
    id: 7,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "A definition of the term 'viscous hydroplaning' is where",
    options: [
      "the airplane rides on standing water.",
      "a film of moisture covers the painted or rubber-coated portion of the runway.",
      "the tires of the airplane are actually riding on a mixture of steam and melted rubber.",
    ],
    answer: 1,
    explain:
      "Either the moisture or the originally slick surface could cause problems, and the combination is especially dangerous. Answer (A) is incorrect because dynamic hydroplaning occurs when the airplane tires ride on standing water. Answer (C) is incorrect because reverted rubber hydroplaning occurs when the tires of the airplane are actually riding on a mixture of steam and melted rubber.",
    reference: "FAA Airplane Flying Handbook - Hydroplaning",
  },
  {
    id: 8,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "Which place in the turbojet engine is subjected to the highest temperature?",
    options: ["Compressor discharge.", "Fuel spray nozzles.", "Turbine inlet."],
    answer: 2,
    explain:
      "The highest temperatures in any turbine engine will occur at the turbine inlet. This TIT (Turbine Inlet Temperature) is usually the limiting factor in the engine operation.",
    reference: "FAA Airplane Flying Handbook - Turbine Engines",
  },
  {
    id: 9,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "What effect, if any, does high ambient temperature have upon the thrust output of a turbine engine?",
    options: [
      "Thrust will be reduced due to the decrease in air density.",
      "Thrust will remain the same, but turbine temperature will be higher.",
      "Thrust will be higher because more heat energy is extracted from the hotter air.",
    ],
    answer: 0,
    explain:
      "Turbine engine thrust varies directly with air density. As air density decreases, so does thrust. An increase in temperature will decrease air density.",
    reference: "FAA Airplane Flying Handbook - Turbine Engines",
  },
  {
    id: 10,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "Compared to dynamic hydroplaning, at what speed does viscous hydroplaning occur when landing on a smooth, wet runway?",
    options: [
      "At approximately 2.0 times the speed that dynamic hydroplaning occurs.",
      "At a lower speed than dynamic hydroplaning.",
      "At the same speed as dynamic hydroplaning.",
    ],
    answer: 1,
    explain:
      "Viscous hydroplaning occurs due to the viscous properties of water. In this type, a thin film of fluid (not more than 1/1,000 of an inch in depth) cannot be penetrated by the tire and the tire rolls on top of the film. This can occur at a much lower speed than dynamic hydroplaning but requires a smooth acting surface.",
    reference: "FAA Airplane Flying Handbook - Hydroplaning",
  },
  {
    id: 11,
    subject: "FAA ATP",
    system: "Airport & Approach Operations",
    q: "Approaching the runway 1 degree below glidepath can add how many feet to the landing distance?",
    options: ["250 feet.", "500 feet.", "1,000 feet."],
    answer: 1,
    explain:
      "On final approach, at a constant airspeed, the glidepath angle and rate of descent is controlled with pitch attitude and elevator. The optimum glidepath angle is 2.5 to 3 degrees whether or not an electronic glidepath reference is being used. On visual approaches, pilots may have a tendency to make flat approaches. A flat approach, however, will increase landing distance and should be avoided. For example, an approach angle of 2 degrees instead of the recommended 3 degrees will add 500 feet to landing distance.",
    reference: "FAA Airplane Flying Handbook - Approach and Landing",
  },
  {
    id: 12,
    subject: "FAA ATP",
    system: "Regulations & Certification",
    q: "You are assigned to ferry a large, three-engine, turbojet-powered airplane from one facility to another to repair an inoperative engine. You know you are restricted to",
    options: [
      "VFR weather for takeoff, en route, and landing.",
      "flight crewmembers only aboard.",
      "a computed takeoff distance to reach V1 that cannot exceed 70 percent of the effective runway length.",
    ],
    answer: 1,
    explain:
      "A commercial operator of large aircraft may conduct a ferry flight of a four-engine airplane or a turbine-engine-powered, three-engine airplane with one engine inoperative, to a base for the purpose of repairing the engine. Several restrictions apply to such flights. These include: 1. The Airplane Flight Manual must include procedures and performance data which allow for the safe operation of such a flight. 2. The initial climb cannot be over thickly-populated areas. 3. Weather conditions at the takeoff and destination airports must be VFR. 4. Only required flight crewmembers may be on board the aircraft.",
    reference: "14 CFR 121.197",
  },
  {
    id: 13,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "What is the resulting performance loss when one engine on a twin-engine airplane fails?",
    options: [
      "Reduction of cruise airspeed by 50 percent.",
      "Reduction of climb by 80 to 90%.",
      "Reduction of all performance by 50 percent.",
    ],
    answer: 1,
    explain:
      "When one engine fails on a light twin, performance is not really halved, but is actually reduced by 80% or more. The performance loss is greater than 50% because an airplane's climb performance is a function of the thrust horsepower, which is in excess of that required for level flight. Answer (A) is incorrect because the power loss affects climb capability much more than it does cruise speed. Answer (C) is incorrect because climb capability is significantly (more than 50%) reduced.",
    reference: "FAA Airplane Flying Handbook - Multiengine Performance",
  },
  {
    id: 14,
    subject: "FAA ATP",
    system: "Airport & Approach Operations",
    q: "Under which condition during the landing roll are the main wheel brakes at maximum effectiveness?",
    options: [
      "When wing lift has been reduced.",
      "At high groundspeeds.",
      "When the wheels are locked and skidding.",
    ],
    answer: 0,
    explain:
      "Wheel brakes are at maximum effectiveness when the weight of the airplane is used to hold the tires in contact with the runway and the rate of wheel deceleration (or slowing) is just below that which would induce a skid. To place the maximum weight on the tires it is necessary to reduce lift as soon as possible after touchdown by lowering the nose wheel to the runway and deploying wing spoilers. Wheel brakes become more effective as an airplane decelerates (or slows down) because of loss of residual lift as the airspeed decreases. Answer (B) is incorrect because, at high ground speeds, the lift is greater and the normal force on the wheels is small, thus the braking friction force is small. Answer (C) is incorrect because, when the wheels are locked and skidding, the braking friction force is small.",
    reference: "FAA Airplane Flying Handbook - Landing Roll",
  },
  {
    id: 15,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "What effect does high relative humidity have upon the maximum power output of modern aircraft engines?",
    options: [
      "Neither turbojet nor reciprocating engines are affected.",
      "Reciprocating engines will experience a significant loss of BHP.",
      "Turbojet engines will experience a significant loss of thrust.",
    ],
    answer: 1,
    explain:
      "While turbojet engines are almost unaffected by high relative humidity, reciprocating engines will experience a significant loss of BHP (Brake Horsepower). Answer (A) is incorrect because both reciprocating and turbojet engines are affected by high relative humidity to some degree. Answer (C) is incorrect because turbojet engines will have a negligible loss of thrust.",
    reference: "FAA Airplane Flying Handbook - Reciprocating Engines",
  },
  {
    id: 16,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "What effect will an increase in altitude have upon the available equivalent shaft horsepower (ESHP) of a turboprop engine?",
    options: [
      "Lower air density and engine mass flow will cause a decrease in power.",
      "Higher propeller efficiency will cause an increase in usable power (ESHP) and thrust.",
      "Power will remain the same but propeller efficiency will decrease.",
    ],
    answer: 0,
    explain:
      "As altitude is increased, the ESHP of a turboprop engine will decrease due to lower engine mass flow and decreased propeller efficiency.",
    reference: "FAA Airplane Flying Handbook - Turboprop Engines",
  },
  {
    id: 17,
    subject: "FAA ATP",
    system: "Regulations & Certification",
    q: "Which operational requirement must be observed when ferrying an air carrier airplane when one of its three turbine engines is inoperative?",
    options: [
      "The weather conditions at takeoff and destination must be VFR.",
      "The flight cannot be conducted between official sunset and official sunrise.",
      "Weather conditions must exceed the basic VFR minimums for the entire route, including takeoff and landing.",
    ],
    answer: 0,
    explain:
      "A commercial operator of large aircraft may conduct a ferry flight of a four-engine airplane or a turbine-engine-powered, three-engine airplane with one engine inoperative, to a base for the purpose of repairing the engine. Several restrictions apply to such flights. These include: 1. The Airplane Flight Manual must include procedures and performance data which allow for the safe operation of such a flight. 2. The initial climb cannot be over thickly-populated areas. 3. Weather conditions at the takeoff and destination airports must be VFR. 4. Only required flight crewmembers may be on board the aircraft. Answer (B) is incorrect because a ferry flight may be conducted after sunset and before sunrise as long as the takeoff and destination airports are VFR. Answer (C) is incorrect because the weather conditions must be VFR only for takeoff and landing.",
    reference: "14 CFR 121.197",
  },
  {
    id: 18,
    subject: "FAA ATP",
    system: "Airport & Approach Operations",
    q: "How should thrust reversers be applied to reduce landing distance for turbojet aircraft?",
    options: ["Immediately after ground contact.", "Immediately prior to touchdown.", "After applying maximum wheel braking."],
    answer: 0,
    explain:
      "Thrust reversers are most effective at high speeds and should be deployed immediately after touchdown.",
    reference: "FAA Airplane Flying Handbook - Landing Performance",
  },
  {
    id: 19,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "Which is the correct symbol for design cruising speed?",
    options: ["V(C).", "V(S).", "V(A)."],
    answer: 0,
    explain:
      "V(C) - design cruising speed. Answer (B) is incorrect because V(S) is the stalling speed or minimum steady flight speed at which the airplane is controllable. Answer (C) is incorrect because V(A) is maneuvering speed.",
    reference: "14 CFR 1.2 - V-Speed Definitions",
  },
  {
    id: 20,
    subject: "FAA ATP",
    system: "Powerplant & Systems",
    q: "The most important restriction to the operation of turbojet or turboprop engines is",
    options: ["limiting compressor speed.", "limiting exhaust gas temperature.", "limiting torque."],
    answer: 1,
    explain:
      "The highest temperatures in any turbine engine will occur at the turbine inlet. This TIT (Turbine Inlet Temperature) is usually the limiting factor in the engine operation. In many engines, TIT is measured indirectly as EGT (Exhaust Gas Temperature). Answer (A) is incorrect because the turbine section is the most critical element of the turbojet engine. Temperature control is more restrictive than compressor speed, which may operate above 10,000 RPM continuously. Answer (C) is incorrect because torque is a performance measure used on turbopropeller airplanes, but not generally applicable to turbojet engines. The most important restriction is temperature, even though in cooler weather a torque limitation may be reached before the temperature limitation in a turbopropeller airplane.",
    reference: "FAA Airplane Flying Handbook - Turbine Engines",
  },
  {
    id: 21,
    subject: "FAA ATP",
    system: "Aerodynamics & Aircraft Performance",
    q: "What effect does an uphill runway slope have upon takeoff performance?",
    options: ["Increases takeoff distance.", "Decreases takeoff speed.", "Decreases takeoff distance."],
    answer: 0,
    explain:
      "An uphill runway will have the effect of decreasing an airplane's rate of acceleration during the takeoff roll thus causing it to reach its takeoff speeds (V(1) and V(R)) further down the runway than would otherwise be the case. An uphill runway will also necessitate an increased V(1) speed in some airplanes.",
    reference: "FAA Airplane Flying Handbook - Takeoff Performance",
  },
];
