import type { Question } from "../../../types";

// 737 MAX 8 - Engines & APU. Original, independently-written questions based
// on general/public 737-family systems knowledge (not sourced from any
// operator-specific or manufacturer-proprietary document) - no company,
// airline, publisher, or person names.
export const B737_ENGINES_APU_QUESTIONS: Question[] = [
  {
    id: 1,
    system: "Engines & APU",
    q: "On this type's turbofan engines, which parameter is generally used as the primary reference for setting and monitoring commanded thrust?",
    options: [
      "N1 (fan/low-pressure rotor speed, expressed as a percentage of its rated maximum)",
      "Oil pressure alone",
      "Exhaust gas temperature alone, with N1 and N2 ignored",
      "Cabin differential pressure",
    ],
    answer: 0,
    explain:
      "N1 - the rotational speed of the fan/low-pressure spool, shown as a percentage of its rated maximum - is the primary parameter pilots use to set and cross-check commanded thrust, with N2, EGT, and other parameters monitored as supporting and limiting indications rather than the primary thrust reference.",
    reference: "Engines - Thrust Setting Parameters",
  },
  {
    id: 2,
    system: "Engines & APU",
    q: "What is the general dual role of the APU on the ground before engine start?",
    options: [
      "It supplies both electrical power and bleed air, letting the aircraft run its systems and start the main engines without external ground equipment",
      "It supplies hydraulic power only, with no electrical or pneumatic function",
      "It exists solely as a backup and cannot be used at all before the engines are started",
      "It can only provide bleed air, never electrical power",
    ],
    answer: 0,
    explain:
      "The APU is designed to make the aircraft self-sufficient on the ground: it supplies electrical power for aircraft systems and bleed air that can be used for cabin conditioning and to pneumatically start the main engines, all without needing an external ground power cart or air source.",
    reference: "APU - General/Description",
  },
  {
    id: 3,
    system: "Engines & APU",
    q: "In a typical pneumatic engine start sequence, what is the general role of bleed air (from the APU or a ground air source)?",
    options: [
      "It drives a pneumatic starter motor that rotates the engine's core up to a self-sustaining speed before fuel and ignition are introduced",
      "It directly ignites the fuel in the combustor with no mechanical starter involved",
      "It is used only to cool the engine during shutdown, not for starting",
      "It powers an electric starter motor instead of a pneumatic one",
    ],
    answer: 0,
    explain:
      "Bleed air routed to a pneumatic starter motor mechanically spins up the engine core through the start sequence; once the engine reaches a sufficient self-sustaining rotational speed, fuel flow and ignition are introduced, and the starter is later disengaged as the engine accelerates to idle on its own.",
    reference: "Engines - Pneumatic Start Sequence",
  },
  {
    id: 4,
    system: "Engines & APU",
    q: "Why might there be a combined operating limitation when the APU is supplying both bleed air and electrical power at the same time?",
    options: [
      "The APU has a finite total power output, so drawing close to its maximum electrical load while also supplying full bleed air can exceed its combined capacity",
      "The APU's bleed air output and electrical output are generated by entirely unrelated, independent power sources",
      "There is no such limitation under any circumstance",
      "Combined use is prohibited outright and never permitted together",
    ],
    answer: 0,
    explain:
      "The APU's mechanical output has to cover both driving its generator and providing bleed air, so a combined limitation (or a requirement to reduce one when the other is at high demand) exists to keep the APU from being asked for more total power than it can safely deliver at once.",
    reference: "APU - Combined Bleed & Electrical Load Limits",
  },
  {
    id: 5,
    system: "Engines & APU",
    q: "Why do engine fire/overheat detection systems typically use two independent sensing loops around the engine rather than just one?",
    options: [
      "Requiring agreement between two independent loops improves reliability and reduces the chance of a false fire warning from a single faulty sensor",
      "The second loop exists purely as an unused spare with no function",
      "Two loops are required only so each loop can monitor a different engine",
      "A single loop would be more reliable, but two are fitted for weight balance reasons only",
    ],
    answer: 0,
    explain:
      "Using two independent detection loops around the engine (rather than one) means a genuine fire/overheat condition is confirmed by both before certain warning logic triggers, and a fault reported by only one loop is more easily identified as a sensor problem rather than a real fire - improving overall reliability and cutting down on spurious fire warnings from a single failed sensing element.",
    reference: "Fire Protection - Engine Fire/Overheat Detection",
  },
  {
    id: 6,
    system: "Engines & APU",
    q: "What is the general purpose of monitoring exhaust gas temperature (EGT) on a turbine engine?",
    options: [
      "To help protect the turbine section from thermal damage, since exceeding a defined EGT limit risks overheating hot-section components",
      "To measure how much fuel remains in the tanks",
      "To determine cabin pressurization altitude",
      "EGT has no relationship to engine health or limits",
    ],
    answer: 0,
    explain:
      "Exhaust gas temperature is one of the key parameters protecting the turbine's hot-section components from thermal damage; staying within the defined EGT limit for a given condition (start, takeoff, or continuous operation) helps ensure those components aren't exposed to more heat than they're designed to tolerate.",
    reference: "Engines - EGT Limits",
  },
  {
    id: 7,
    system: "Engines & APU",
    q: "What is the general purpose of monitoring engine oil pressure, temperature, and quantity together?",
    options: [
      "Together they give an overall picture of the lubrication system's health, helping the crew catch a developing mechanical problem before it becomes a failure",
      "Oil parameters are monitored only for record-keeping, with no operational significance",
      "Only oil quantity matters; pressure and temperature are irrelevant",
      "These parameters are used exclusively to compute fuel flow",
    ],
    answer: 0,
    explain:
      "Oil pressure, temperature, and quantity together reflect the health of the engine's lubrication and cooling system - a falling quantity, rising temperature, or falling pressure can each independently point to a developing mechanical problem, so monitoring all three gives the crew an early warning that a single parameter alone might miss.",
    reference: "Engines - Oil System Monitoring",
  },
  {
    id: 8,
    system: "Engines & APU",
    q: "What is the general purpose of monitoring engine vibration levels in flight?",
    options: [
      "Elevated vibration can indicate developing mechanical damage or imbalance inside the engine, giving the crew (and maintenance) an early warning sign",
      "Vibration monitoring exists purely to control cabin noise levels",
      "It is used only to measure outside air turbulence",
      "It has no diagnostic value and is displayed only as a formality",
    ],
    answer: 0,
    explain:
      "A rotating turbine engine that develops internal damage or imbalance - such as a damaged blade - often shows it first as increased vibration, so monitoring vibration levels gives an early indication of a developing mechanical problem, sometimes before it shows up in other parameters.",
    reference: "Engines - Vibration Monitoring",
  },
  {
    id: 9,
    system: "Engines & APU",
    q: "What is the general purpose of automatic APU shutdown protections, such as for overspeed, overtemperature, or a detected fire?",
    options: [
      "They automatically shut the APU down when a genuinely hazardous condition is detected, without requiring a crew member to notice and react manually",
      "They exist only to save fuel during normal operation",
      "They are purely cosmetic and have no actual shutdown function",
      "They only function while the APU is being used for ground air conditioning",
    ],
    answer: 0,
    explain:
      "Because the APU can run unattended (with no one directly monitoring it the way a pilot monitors engine instruments), automatic protective shutdown logic for conditions like overspeed, overtemperature, or a detected fire is built in specifically so a genuinely hazardous condition is addressed immediately, without depending on a crew member noticing and reacting manually in time.",
    reference: "APU - Automatic Protective Shutdowns",
  },
  {
    id: 10,
    system: "Engines & APU",
    q: "What is the general purpose of an engine start valve during the start sequence?",
    options: [
      "It opens to admit pneumatic air to the starter to begin engine rotation, then closes automatically once the engine reaches a self-sustaining speed",
      "It stays open continuously throughout the entire flight",
      "It controls fuel flow rather than air flow",
      "It is used only to shut down the engine, never to start it",
    ],
    answer: 0,
    explain:
      "The start valve is what actually admits pneumatic air to the starter motor at the beginning of the start sequence; once the engine has accelerated to a self-sustaining rotational speed on its own combustion, the valve automatically closes, cutting off air to the (now unneeded) starter as the engine continues accelerating to idle by itself.",
    reference: "Engines - Start Valve",
  },
  {
    id: 11,
    system: "Engines & APU",
    q: "What is the general purpose of a thrust reverser on a turbofan engine?",
    options: [
      "It redirects a portion of engine exhaust/fan air forward to help decelerate the aircraft after touchdown, supplementing wheel braking",
      "It increases forward thrust during takeoff",
      "It is used only during cruise flight to improve fuel efficiency",
      "It permanently shuts down the engine once deployed",
    ],
    answer: 0,
    explain:
      "A thrust reverser redirects a portion of the engine's airflow forward (rather than rearward), producing a deceleration force that supplements wheel braking during the landing roll or a rejected takeoff - it's generally restricted to ground use and stowed again before the aircraft taxis at low speed.",
    reference: "Engines - Thrust Reversers",
  },
  {
    id: 12,
    system: "Engines & APU",
    q: "Why do modern turbofan engines typically use a dual-channel electronic engine control (EEC/FADEC) architecture?",
    options: [
      "So a fault in one control channel doesn't leave the engine with no electronic control at all, since the second channel can take over managing the engine",
      "The second channel exists only to control cabin temperature",
      "Dual channels are fitted purely to reduce fuel burn, with no redundancy purpose",
      "Only one channel is ever functional; the second is a non-functional spare with no automatic switchover",
    ],
    answer: 0,
    explain:
      "A dual-channel electronic engine control is built so that if one channel develops a fault, the system automatically transfers full engine control to the healthy remaining channel, protecting against a single electronic fault leaving the engine without any computerized control of fuel scheduling and limit protection.",
    reference: "Engines - Dual-Channel Electronic Engine Control",
  },
  {
    id: 13,
    system: "Engines & APU",
    q: "What is the general purpose of an engine oil scavenge pump, separate from the pressure pump that supplies oil to bearings and gears?",
    options: [
      "It returns oil that has passed through the bearing/gear areas back to the oil tank, since oil can't simply be left to accumulate wherever it drains to inside the engine",
      "It supplies fresh oil under pressure to the bearings, duplicating the pressure pump's job",
      "It has no real function and exists only as a backup pressure pump",
      "It pumps fuel rather than oil",
    ],
    answer: 0,
    explain:
      "After oil has done its job lubricating and cooling bearings and gears, it has to be actively recovered from wherever it collects inside the engine and returned to the tank; scavenge pumps handle that return trip, which is a distinct job from the pressure pump that pushes fresh oil out to those components in the first place.",
    reference: "Engines - Oil Scavenge Pumps",
  },
  {
    id: 14,
    system: "Engines & APU",
    q: "What is the general purpose of an APU inlet door that opens automatically rather than staying open at all times?",
    options: [
      "Keeping it closed except when the APU is running (or about to run) reduces drag and keeps foreign objects/moisture out of the APU compartment the rest of the time",
      "The door exists solely to control cabin temperature",
      "The door must always be manually opened by ground crew before every APU start",
      "It has no aerodynamic or protective purpose at all",
    ],
    answer: 0,
    explain:
      "Automatically opening the APU inlet door only when the APU is starting or running (and keeping it closed the rest of the time) reduces the drag a permanently open inlet would create and helps keep debris, water, or foreign objects out of the APU compartment when the unit isn't in use.",
    reference: "APU - Inlet Door Operation",
  },
  {
    id: 15,
    system: "Engines & APU",
    q: "Unlike a piston twin, where losing one engine can create a distinctly more hazardous 'critical engine' asymmetric condition, why is that distinction generally much less pronounced on a twin-turbofan jet transport?",
    options: [
      "The two engines are mounted close to the fuselage centerline with relatively little offset, and yaw/rudder authority is sized to handle an engine failure from either side without one side being meaningfully worse than the other",
      "Twin-turbofan jets are incapable of ever losing an engine in flight",
      "There is no rudder or directional control available on a twin-turbofan jet",
      "Both engines are mechanically interconnected so a failure of one automatically stops the other",
    ],
    answer: 0,
    explain:
      "A traditional light piston twin's outboard-mounted, opposite-rotating (or same-rotating) propellers can make losing one engine notably worse than losing the other, but a podded twin-turbofan transport generally has its engines close enough to the centerline, with rudder/directional control authority sized for an engine failure from either side, that there isn't the same kind of pronounced 'critical engine' distinction to plan around.",
    reference: "Engines - No Pronounced Critical Engine on a Twin-Turbofan",
  },
];
