import type { Question } from "../../../types";

// 737 MAX 8 - Engines & APU. Original, independently-written questions based
// on general/public 737-family systems knowledge (not sourced from any
// operator-specific or manufacturer-proprietary document) - no company,
// airline, publisher, or person names.
export const B737_ENGINES_APU_QUESTIONS: Question[] = [
  {
    id: 1,
    system: "Engines & APU",
    q: "On this type's turbofan engines, which parameter is generally used as the primary reference for setting and monitoring commanded thrust?",
    options: [
      "N1 (fan/low-pressure rotor speed, expressed as a percentage of its rated maximum)",
      "Oil pressure alone",
      "Exhaust gas temperature alone, with N1 and N2 ignored",
      "Cabin differential pressure",
    ],
    answer: 0,
    explain:
      "N1 - the rotational speed of the fan/low-pressure spool, shown as a percentage of its rated maximum - is the primary parameter pilots use to set and cross-check commanded thrust, with N2, EGT, and other parameters monitored as supporting and limiting indications rather than the primary thrust reference.",
    reference: "Engines - Thrust Setting Parameters",
  },
  {
    id: 2,
    system: "Engines & APU",
    q: "What is the general dual role of the APU on the ground before engine start?",
    options: [
      "It supplies both electrical power and bleed air, letting the aircraft run its systems and start the main engines without external ground equipment",
      "It supplies hydraulic power only, with no electrical or pneumatic function",
      "It exists solely as a backup and cannot be used at all before the engines are started",
      "It can only provide bleed air, never electrical power",
    ],
    answer: 0,
    explain:
      "The APU is designed to make the aircraft self-sufficient on the ground: it supplies electrical power for aircraft systems and bleed air that can be used for cabin conditioning and to pneumatically start the main engines, all without needing an external ground power cart or air source.",
    reference: "APU - General/Description",
  },
  {
    id: 3,
    system: "Engines & APU",
    q: "In a typical pneumatic engine start sequence, what is the general role of bleed air (from the APU or a ground air source)?",
    options: [
      "It drives a pneumatic starter motor that rotates the engine's core up to a self-sustaining speed before fuel and ignition are introduced",
      "It directly ignites the fuel in the combustor with no mechanical starter involved",
      "It is used only to cool the engine during shutdown, not for starting",
      "It powers an electric starter motor instead of a pneumatic one",
    ],
    answer: 0,
    explain:
      "Bleed air routed to a pneumatic starter motor mechanically spins up the engine core through the start sequence; once the engine reaches a sufficient self-sustaining rotational speed, fuel flow and ignition are introduced, and the starter is later disengaged as the engine accelerates to idle on its own.",
    reference: "Engines - Pneumatic Start Sequence",
  },
  {
    id: 4,
    system: "Engines & APU",
    q: "Why might there be a combined operating limitation when the APU is supplying both bleed air and electrical power at the same time?",
    options: [
      "The APU has a finite total power output, so drawing close to its maximum electrical load while also supplying full bleed air can exceed its combined capacity",
      "The APU's bleed air output and electrical output are generated by entirely unrelated, independent power sources",
      "There is no such limitation under any circumstance",
      "Combined use is prohibited outright and never permitted together",
    ],
    answer: 0,
    explain:
      "The APU's mechanical output has to cover both driving its generator and providing bleed air, so a combined limitation (or a requirement to reduce one when the other is at high demand) exists to keep the APU from being asked for more total power than it can safely deliver at once.",
    reference: "APU - Combined Bleed & Electrical Load Limits",
  },
  {
    id: 5,
    system: "Engines & APU",
    q: "Why do engine fire/overheat detection systems typically use two independent sensing loops around the engine rather than just one?",
    options: [
      "Requiring agreement between two independent loops improves reliability and reduces the chance of a false fire warning from a single faulty sensor",
      "The second loop exists purely as an unused spare with no function",
      "Two loops are required only so each loop can monitor a different engine",
      "A single loop would be more reliable, but two are fitted for weight balance reasons only",
    ],
    answer: 0,
    explain:
      "Using two independent detection loops around the engine (rather than one) means a genuine fire/overheat condition is confirmed by both before certain warning logic triggers, and a fault reported by only one loop is more easily identified as a sensor problem rather than a real fire - improving overall reliability and cutting down on spurious fire warnings from a single failed sensing element.",
    reference: "Fire Protection - Engine Fire/Overheat Detection",
  },
];
