import type { Question } from "../../../types";

// Canada TC ATPL question bank, Batch 26 -- Section 8: Meteorology
// (SAMRA), third pass. Original questions written from meteorological
// principles, the TC AIM (MET), and the TP 690 syllabus (topic
// headings only, no sample questions). Covers local winds, the
// tropopause, precipitation-type icing, and forecast product
// mechanics not yet addressed in batches 8 or 18. Not transcribed or
// adapted from any commercial test-prep publisher.
export const CANADA_TC_ATPL_BATCH_26_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "An anabatic wind, the counterpart to a katabatic wind, is generated by",
    options: [
      "overnight radiational cooling of a sloping surface, causing the air in contact with it to cool, become denser, and drain downslope.",
      "the same downslope, gravity-driven mechanism as a katabatic wind, with 'anabatic' simply being an alternate regional name for the identical phenomenon.",
      "daytime solar heating of a sloping surface, causing the air in contact with it to warm, become less dense, and flow upslope.",
      "a large-scale frontal system passing over mountainous terrain, unrelated to any local, terrain-driven heating or cooling effect.",
    ],
    answer: 2,
    explain:
      "An anabatic wind is the daytime mirror image of a katabatic wind: solar heating warms the air in contact with a sloping surface, making it less dense than the surrounding air at the same altitude, and that warmed air rises upslope -- the reverse mechanism (and the reverse time of day) from katabatic drainage flow, which is driven by nighttime cooling and gravity rather than daytime heating and buoyancy.",
    reference: "TP 690 Section 8 - Meteorology, Local Winds",
  },
  {
    id: 2,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "A Föhn (or Chinook) wind, experienced on the lee (downwind) side of a mountain range, is characterized by",
    options: [
      "a wind entirely unrelated to any moisture or adiabatic temperature change, driven purely by pressure gradient force across the mountain range and nothing else.",
      "a comparatively cold, moist wind, resulting from air that gained moisture descending the lee slope faster than it lost moisture on the windward side -- the reverse of the warm, dry result a Föhn or Chinook wind actually produces.",
      "a wind that only occurs on the windward (upwind) side of a mountain range, never on the lee side where the Föhn or Chinook effect is actually observed.",
      "a comparatively warm, dry wind, resulting from air that lost moisture through precipitation on the windward slope and then warmed adiabatically faster descending the lee slope than it cooled ascending the windward side.",
    ],
    answer: 3,
    explain:
      "A Föhn/Chinook wind's characteristic warmth and dryness comes from an asymmetry in the moist and dry adiabatic lapse rates: air rising on the windward side cools at the (slower) moist adiabatic rate once saturated, dropping much of its moisture as precipitation, but then descends the lee slope dry, warming at the (faster) dry adiabatic rate the whole way down -- so it arrives at the base of the lee slope noticeably warmer and drier than it started, a well-known and sometimes dramatic local temperature effect.",
    reference: "TP 690 Section 8 - Meteorology, Local Winds",
  },
  {
    id: 3,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Wind speed in the upper atmosphere is generally observed to be",
    options: [
      "at its maximum near the tropopause, decreasing at a relatively constant rate both above and below it.",
      "essentially constant with altitude throughout the troposphere and stratosphere, with no meaningful maximum at any particular level.",
      "unrelated to the tropopause's location, and determined solely by surface pressure gradient regardless of altitude.",
      "at its minimum near the tropopause, increasing at a relatively constant rate both above and below it.",
    ],
    answer: 0,
    explain:
      "The tropopause -- the boundary between the troposphere and the stratosphere, where temperature stops decreasing with height -- is typically also where wind speed peaks, with the jet stream cores found at or near this level; wind speed then tends to decrease at a fairly constant rate moving away from the tropopause in either direction, a relationship used alongside upper wind/temperature and significant weather charts to help assess the likelihood of clear air turbulence at a given altitude.",
    reference: "TC AIM MET 11.1",
  },
  {
    id: 4,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Thermal (convective) turbulence is distinguished from mechanical turbulence in that thermal turbulence is generated by",
    options: [
      "the exact same physical mechanism as mechanical turbulence, with the two terms simply describing the same phenomenon under different regional names.",
      "rising and sinking currents driven by uneven surface heating, while mechanical turbulence results from wind flowing over or around physical obstructions such as terrain or buildings.",
      "wind flowing over or around physical obstructions such as terrain or buildings, while mechanical turbulence is driven by uneven surface heating.",
      "changes in magnetic variation at altitude, with mechanical turbulence instead resulting from changes in air pressure, unrelated to convection or airflow over terrain in either case.",
    ],
    answer: 1,
    explain:
      "Thermal turbulence arises from convection: uneven surface heating creates rising thermals (and compensating sinking air) that an aircraft flying through experiences as bumpiness, most pronounced on warm, sunny days over varied terrain. Mechanical turbulence is a fundamentally different, purely mechanical process -- wind disturbed by flowing over or around physical obstacles (terrain, buildings, or other structures) -- and the two mechanisms are often both present and reinforcing each other, but are distinct in origin.",
    reference: "TP 690 Section 8 - Meteorology, Turbulence",
  },
  {
    id: 5,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Frontal (or precipitation-induced) fog can form when",
    options: [
      "the ground radiates heat away on a calm, clear night with no frontal system or precipitation involved at all -- the mechanism behind radiation fog rather than the frontal fog described here.",
      "very cold air moves out over considerably warmer open water, evaporating moisture that quickly condenses into visible fog.",
      "relatively warm precipitation falls through a shallow, cooler layer of air near the surface ahead of an approaching front, raising that layer's humidity to saturation.",
      "warm, moist air moves horizontally over a colder surface, unrelated to any precipitation falling from cloud above at the time.",
    ],
    answer: 2,
    explain:
      "Frontal fog is specifically tied to precipitation and an approaching frontal system: as relatively warm rain or drizzle falls through a shallower, cooler layer of air near the surface ahead of the front, some of it evaporates, adding moisture to that cool layer until it reaches saturation and fog forms -- a mechanism distinct from radiation fog's calm-night surface cooling, advection fog's horizontal surface contact cooling, or steam fog's cold-air-over-warm-water evaporation.",
    reference: "TP 690 Section 8 - Meteorology, Fog",
  },
  {
    id: 6,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Freezing drizzle and freezing rain, both hazardous icing precipitation types, are generally distinguished by",
    options: [
      "freezing drizzle and freezing rain having identical formation mechanisms, differing only in droplet size for reasons unrelated to cloud type or vertical temperature profile.",
      "freezing rain occurring only at temperatures well below -20 degrees Celsius, while freezing drizzle occurs only at temperatures at or above 0 degrees Celsius.",
      "freezing drizzle occurring only in association with thunderstorms, while freezing rain occurs only in stable stratiform conditions, the reverse of the usual association.",
      "freezing drizzle forming from small droplets within a shallow, stable stratiform cloud layer, while freezing rain typically forms as snow melts falling through a warm layer aloft and then refreezes on contact with a subfreezing surface layer.",
    ],
    answer: 3,
    explain:
      "Freezing drizzle typically forms from small droplets within a shallow, stable stratiform cloud layer that never fully develops the vertical structure needed to produce true rain, remaining supercooled as it falls to a subfreezing surface. Freezing rain, by contrast, typically involves precipitation that starts as snow, melts completely falling through a warm layer aloft, and then becomes supercooled again passing through a shallower cold layer near the surface before freezing on contact -- a distinct vertical temperature profile from freezing drizzle's simpler, single-layer stratiform origin.",
    reference: "TP 690 Section 8 - Meteorology, Icing",
  },
  {
    id: 7,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Structural airframe icing risk from supercooled water droplets is generally considered greatest in a temperature range of approximately",
    options: [
      "0 degrees Celsius to -20 degrees Celsius, with liquid water becoming rare at colder temperatures where droplets have typically already frozen into ice crystals.",
      "10 degrees Celsius to 20 degrees Celsius, well above freezing, since icing risk in this range is considered entirely independent of temperature and of any supercooled liquid water in cloud.",
      "exactly 0 degrees Celsius only, with no measurable icing risk considered to exist at any temperature below that single specific value.",
      "-40 degrees Celsius to -60 degrees Celsius, since supercooled liquid water is considered most abundant at these very low temperatures aloft.",
    ],
    answer: 0,
    explain:
      "Structural icing depends on the presence of supercooled liquid water -- water that remains liquid below its normal freezing point -- which is most commonly found roughly between 0 degrees Celsius and -20 degrees Celsius; at much colder temperatures, cloud water increasingly exists as ice crystals rather than supercooled liquid droplets, meaningfully reducing the structural icing risk even though other cold-weather hazards (such as ice fog) can still occur.",
    reference: "TP 690 Section 8 - Meteorology, Icing",
  },
  {
    id: 8,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Low-level wind shear associated with a temperature inversion (for example, on a calm, clear night with a shallow surface-based inversion) is significant because",
    options: [
      "wind shear associated with a temperature inversion occurs only at cruising altitude, with no relevance to the takeoff or approach phases of flight, despite the inversion typically forming near the surface.",
      "wind speed and direction can differ substantially between the surface and just above the inversion, creating a shear layer that can affect an aircraft during takeoff or approach.",
      "a temperature inversion has no relationship to wind shear at all, and the two are considered entirely unrelated atmospheric phenomena in every case.",
      "temperature inversions always eliminate wind shear entirely, making them one of the safest possible atmospheric conditions for takeoff and landing.",
    ],
    answer: 1,
    explain:
      "A shallow surface-based inversion, common on calm, clear nights, effectively decouples the light, near-calm surface wind from the stronger wind flowing just above the inversion, which can no longer mix down through the stable layer -- an aircraft climbing out through or descending into that layer can encounter a real, sometimes abrupt change in wind speed and/or direction over a short vertical distance, exactly the kind of low-level wind shear that's a recognized hazard during takeoff and approach.",
    reference: "TP 690 Section 8 - Meteorology, Wind",
  },
  {
    id: 9,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "For each of its forecast periods, a Graphic Area Forecast (GFA) issue consists of a pair of charts covering",
    options: [
      "only icing and turbulence, with cloud, weather, and freezing level information not included anywhere in the GFA product.",
      "temperature and dewpoint on one chart, and wind and pressure on the other, with cloud and icing information entirely excluded from the GFA.",
      "clouds and weather on one chart, and icing, turbulence, and freezing level on the other.",
      "only clouds and weather, with icing, turbulence, and freezing level information not included anywhere in the GFA product.",
    ],
    answer: 2,
    explain:
      "Each GFA forecast period is depicted with two complementary charts: one showing clouds and weather, and a separate one showing icing, turbulence, and freezing level -- together giving a fuller pre-flight planning picture than either chart alone, issued four times daily (roughly every six hours) with charts covering the beginning, six hours, and twelve hours into each forecast period.",
    reference: "TC AIM MET 4.0-4.2",
  },
  {
    id: 10,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "In a METAR, a reported wind of '18025G40KT' indicates",
    options: [
      "wind gusting from 180 degrees to 400 degrees, a wide directional variation, at a constant 25 knots.",
      "wind from 180 degrees at a steady 25 knots, with no gusting occurring, and 'G40' referring to a separate ground visibility value.",
      "wind of 25 knots with 40 percent cloud cover, unrelated to any gust value at all.",
      "wind from 180 degrees (true north, per the international METAR convention) at 25 knots, gusting to 40 knots.",
    ],
    answer: 3,
    explain:
      "In METAR wind group notation, the first three digits give wind direction, the next two (or three) digits give sustained wind speed, and a 'G' followed by additional digits gives the gust value when gusts meet the reporting threshold -- so '18025G40KT' is wind from 180 degrees at 25 knots, gusting to 40 knots, with 'KT' confirming the units as knots (METAR wind direction is typically reported relative to true north internationally, though Canadian aerodrome forecasts and ATIS/tower wind reports are given in the pilot's more operationally useful magnetic reference).",
    reference: "TC AIM MET 8.1",
  },
  {
    id: 11,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "A TAF is generally issued as an amendment (TAF AMD) when",
    options: [
      "actual or expected conditions cross defined thresholds for ceiling, visibility, weather, wind, or the onset of low-level wind shear -- whether conditions are turning out better or worse than originally forecast.",
      "exactly 6 hours have elapsed since the original TAF was issued, regardless of whether any of the forecast conditions have actually changed.",
      "conditions are turning out worse than originally forecast, but never when conditions are turning out better than forecast, since an improving trend does not warrant an amendment.",
      "the forecaster wishes to extend the TAF's total valid period beyond what was originally published, with no relationship to any change in forecast conditions.",
    ],
    answer: 0,
    explain:
      "TAF amendment criteria are threshold-based, not one-directional: an amendment is issued whenever ceiling, visibility, weather, wind speed/direction, or the onset of low-level wind shear crosses a defined threshold from what was previously forecast -- and that applies whether the change means conditions are now expected to be better or worse than the original forecast, not only when things are deteriorating.",
    reference: "TC AIM MET 8.1",
  },
  {
    id: 12,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "In the northern hemisphere, surface wind generally circulates around a high-pressure system",
    options: [
      "counterclockwise and inward toward the centre, while circulating clockwise and outward around a low-pressure system, the reverse of the usual pattern.",
      "clockwise and outward from the centre, while circulating counterclockwise and inward around a low-pressure system.",
      "in a direction that depends entirely on the season, reversing between summer and winter for both high- and low-pressure systems.",
      "in the same clockwise, outward direction around both high- and low-pressure systems, with no directional difference between the two.",
    ],
    answer: 1,
    explain:
      "In the northern hemisphere, the Coriolis effect combined with the pressure gradient produces clockwise, outward-spiraling flow around a high-pressure centre and counterclockwise, inward-spiraling flow around a low-pressure centre -- a relationship (sometimes summarized as Buys Ballot's law, with the low pressure to one's left when facing downwind in that hemisphere) that reverses in the southern hemisphere but doesn't otherwise change with season.",
    reference: "TP 690 Section 8 - Meteorology, Pressure and Wind",
  },
  {
    id: 13,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "The freezing level -- the altitude at which temperature first reaches 0 degrees Celsius -- for a given area and time can generally be determined from",
    options: [
      "a NOTAM, since freezing level is treated as an aerodrome-specific administrative notice rather than a meteorological forecast element.",
      "a METAR alone, since surface observations are considered sufficient to determine freezing level at any altitude without any forecast product.",
      "the icing, turbulence, and freezing level chart included in the GFA, which depicts the freezing level directly.",
      "the clouds and weather chart included in the GFA, since freezing level information is not depicted anywhere else in the GFA product.",
    ],
    answer: 2,
    explain:
      "Freezing level is specifically part of the GFA's icing/turbulence/freezing level chart (the companion to the clouds-and-weather chart), which depicts where the 0-degree-Celsius level is expected across the forecast area -- a forecast, area-based product suited to flight planning, distinct from a METAR's point-in-time surface observation or a NOTAM's administrative/hazard notice function.",
    reference: "TC AIM MET 4.0",
  },
  {
    id: 14,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Warm air advection (relatively warm air moving into a region, replacing cooler air) tends to have a stabilizing effect on the atmosphere primarily because it",
    options: [
      "has no effect on atmospheric stability at all, with stability determined solely by surface moisture content regardless of any temperature advection.",
      "always produces widespread convective thunderstorm activity, which is itself the defining characteristic of a stabilizing atmosphere.",
      "cools the surface air directly, steepening the lapse rate and increasing atmospheric instability rather than decreasing it.",
      "warms the air aloft relative to the surface, reducing the temperature difference (and therefore the lapse rate) between the surface and altitude.",
    ],
    answer: 3,
    explain:
      "Warm air advection generally warms the air aloft (or arrives first at altitude ahead of any surface warming), reducing the temperature difference between the surface and higher levels and, with it, the environmental lapse rate -- a shallower lapse rate corresponds to a more stable atmosphere, the opposite effect of cold air advection, which cools the upper air relative to the surface, steepens the lapse rate, and tends to destabilize the atmosphere.",
    reference: "TP 690 Section 8 - Meteorology, Stability",
  },
  {
    id: 15,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "Surface wind speed typically follows a diurnal pattern in which it",
    options: [
      "increases during the afternoon, as daytime heating promotes vertical mixing that brings stronger winds from aloft down to the surface, and decreases at night as the surface layer decouples from the wind above.",
      "decreases during the afternoon due to daytime heating, and increases sharply at night as the atmosphere becomes more turbulent after sunset.",
      "is determined solely by the passage of frontal systems, with no diurnal (day/night) pattern occurring independent of frontal activity.",
      "remains essentially constant throughout the day and night, with diurnal heating and cooling having no measurable effect on surface wind speed.",
    ],
    answer: 0,
    explain:
      "Daytime heating generates thermal turbulence and vertical mixing that brings some of the generally stronger wind found aloft down to the surface, typically producing a stronger and gustier surface wind through the afternoon; overnight, as the ground cools and a stable layer often forms near the surface, that mixing weakens and the surface effectively decouples from the wind above, commonly producing lighter and steadier (though sometimes still locally variable) surface wind at night.",
    reference: "TP 690 Section 8 - Meteorology, Wind",
  },
  {
    id: 16,
    subject: "Canada TC ATPL",
    system: "Meteorology",
    q: "A cap cloud, observed sitting directly over and clinging to a mountain summit on the windward side, forms when",
    options: [
      "moist air descends the lee side of the mountain and warms adiabatically, reaching saturation as it descends rather than as it rises.",
      "moist air is forced to rise and cool adiabatically as it approaches and flows over the mountain, reaching saturation right at or near the summit.",
      "radiational cooling of the mountain's rock surface overnight chills the surrounding air directly, independent of any airflow over the terrain.",
      "a cap cloud is, by definition, identical in formation mechanism and appearance to a standing lenticular cloud found downwind of the mountain.",
    ],
    answer: 1,
    explain:
      "A cap cloud forms on the windward, ascending side of the terrain: as moist air is forced upward approaching the mountain, it cools adiabatically and reaches saturation right around the summit, forming a cloud that appears to cling to and cap the peak -- a distinct visual signature and formation mechanism from a standing lenticular cloud, which forms further downwind in the crests of a wave pattern set up in the lee of the mountain, or from a rotor cloud, which marks a separate turbulent circulation beneath that wave.",
    reference: "TP 690 Section 8 - Meteorology, Turbulence",
  },
];
