import type { Question } from "../../../types";

// Canada TC ATPL question bank, Batch 74 -- Section 9: Radio
// Communications and Aids to Navigation, eighth pass. Original
// questions written from the TP 690 syllabus (topic headings only,
// no sample questions), the CARs, and the TC AIM 2026-1. Covers the
// NDB (LF/MF) vs VOR (VHF) band trade-off, precipitation static
// affecting ADF/NDB reception, multi-constellation GNSS, the
// discontinuation of GPS Selective Availability, DME ground station
// interrogation capacity, the HF antenna coupler, PIREPs, SAR
// alerting phases, the GNSS L1 C/A code, callsign confusion,
// standard radio check readability, the VOR test facility (VOT),
// automatic VOR ground station monitoring, SATCOM's geostationary
// polar coverage gap, the FSS advisory role vs ATC, and the
// Aerodrome Traffic Frequency vs Mandatory Frequency distinction --
// topics not yet addressed in batches 10, 17, 25, 34, 44, 54, or 64.
// Not transcribed or adapted from any commercial test-prep
// publisher.
export const CANADA_TC_ATPL_BATCH_74_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "NDBs operate in the low/medium frequency (LF/MF) band, while VOR operates in the VHF band. A practical consequence of this difference is that, compared to VOR, an NDB signal",
    options: [
      "provides a more accurate bearing than VOR under all conditions, which is why VOR has been progressively decommissioned in favour of NDBs.",
      "is completely immune to atmospheric noise and precipitation static, unlike VOR, a claim that overstates ADF's actual vulnerability profile, since low-frequency NDB signals are in fact particularly susceptible to atmospheric noise, precipitation static, and thunderstorm activity.",
      "can follow the curvature of the Earth (ground wave propagation) and is not strictly limited to line-of-sight range, but is more susceptible to atmospheric noise, precipitation static, and terrain-related bearing errors.",
      "is strictly limited to line-of-sight range in the same way as VOR, with no ground wave propagation advantage at all.",
    ],
    answer: 2,
    explain:
      "Because NDBs transmit in the LF/MF band, their signal can propagate as a ground wave that follows the Earth's curvature, giving useful reception well beyond line-of-sight range; however, this same lower frequency makes NDB/ADF reception considerably more susceptible to atmospheric noise, precipitation static, and terrain-induced bearing errors than the higher-frequency, line-of-sight VHF signal used by VOR, which is one reason VOR is generally regarded as the more accurate and reliable of the two.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Radio Wave Propagation",
  },
  {
    id: 2,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "Precipitation static (P-static), generated by an aircraft's airframe accumulating static charge while flying through precipitation, ice crystals, or dust, degrades ADF/NDB bearing reception primarily by",
    options: [
      "improving ADF bearing accuracy by providing an additional, stronger reference signal for the receiver to track, which mischaracterizes the interference as helpful rather than as unwanted electrical noise capable of masking the weak NDB signal the receiver is trying to track.",
      "affecting only VHF communication radios, with no measurable effect on the LF/MF-band ADF receiver.",
      "physically altering the NDB ground station's transmitted signal before it ever reaches the aircraft.",
      "introducing electrical noise directly into the low-frequency ADF receiver, which can mask the weak NDB signal, cause erratic needle movement, or in severe cases make the bearing unusable.",
    ],
    answer: 3,
    explain:
      "P-static is generated when an airframe accumulates static electrical charge from friction with precipitation, ice crystals, or dust, and the resulting electrical noise couples readily into the sensitive, low-frequency ADF receiver -- this can mask the already weak NDB signal, cause the bearing needle to swing erratically, or in severe cases make the indicated bearing unusable, in addition to producing crackling or static noise on VHF communication receivers.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: NDB/ADF Errors",
  },
  {
    id: 3,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "A modern multi-constellation GNSS receiver, able to use signals from GPS, GLONASS, Galileo, and/or BeiDou rather than GPS alone, generally provides an operational benefit of",
    options: [
      "improved satellite geometry and availability, since a greater number of visible satellites from multiple constellations reduces the likelihood of an unacceptable position solution due to poor geometry or a masked satellite, particularly in challenging environments.",
      "no operational benefit at all, since only one constellation's satellites can be used by a receiver at any given time.",
      "guaranteed immunity from ionospheric delay, which affects GPS signals but not signals from any other constellation.",
      "a requirement to disable all other constellations whenever GPS satellites are available, to avoid signal conflicts, a restriction that does not exist operationally, since modern multi-constellation receivers are specifically designed to combine signals from several constellations simultaneously rather than to disable all but one.",
    ],
    answer: 0,
    explain:
      "By drawing on satellites from multiple independent constellations rather than GPS alone, a multi-constellation receiver has access to a larger pool of visible satellites at any given time, improving overall satellite geometry and availability and reducing the likelihood that a temporarily poor geometry, a masked satellite, or a constellation-specific outage degrades the position solution -- ionospheric delay affects signals from every constellation and is not eliminated by using more than one.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: GNSS",
  },
  {
    id: 4,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "Selective Availability, a deliberate degradation of civil GPS signal accuracy formerly applied by the United States for military reasons, was discontinued in 2000. Its discontinuation",
    options: [
      "had no effect on civil GPS accuracy, since Selective Availability only ever applied to military receivers.",
      "significantly improved the achievable accuracy of civil GPS positioning, which had previously been intentionally limited to a much coarser level for non-military users.",
      "immediately eliminated the need for any form of GNSS augmentation, such as SBAS, since unaugmented civil GPS became fully precision-approach capable on its own.",
      "was reversed several years later, meaning Selective Availability remains active on civil GPS signals today.",
    ],
    answer: 1,
    explain:
      "Selective Availability was a deliberate degradation the United States applied to the civil GPS signal, intentionally limiting the accuracy available to non-military users for security reasons; its discontinuation in May 2000 substantially and immediately improved the accuracy available to civil GPS receivers, though unaugmented GPS still did not, on its own, meet the accuracy and integrity requirements for GNSS-based precision approach guidance, which is part of why augmentation systems such as SBAS and GBAS were subsequently developed.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: GNSS",
  },
  {
    id: 5,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "A ground-based DME transponder has a practical limit on the number of aircraft it can reliably serve at once primarily because",
    options: [
      "DME ground stations can physically only transmit one reply per minute, regardless of how many aircraft are interrogating.",
      "each aircraft using a DME station's signal permanently reduces that station's maximum range for every other user.",
      "each interrogating aircraft's transponder replies add to the total number of pulse pairs the ground station must process, and once this interrogation traffic approaches the station's reply capacity, its ability to reliably answer every aircraft (including new ones trying to lock on) degrades.",
      "DME ground stations are limited by regulation to serving a single aircraft at a time, with all others automatically refused service, a limitation that does not reflect how DME actually works, since a ground station replies to many interrogating aircraft simultaneously up to the point where accumulated interrogation traffic begins to approach its reply capacity.",
    ],
    answer: 2,
    explain:
      "A DME ground station replies individually to interrogations from every aircraft using it, and as the number of aircraft interrogating a given station increases, the total reply traffic the station must handle rises correspondingly; once this approaches the station's processing and reply capacity, both existing users and aircraft attempting to newly lock onto the station can experience degraded reliability, which is why DME channel loading is a real engineering constraint, particularly in high-density airspace near a single popular facility.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: DME",
  },
  {
    id: 6,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "An HF communication radio's antenna coupler (antenna tuning unit) is used primarily to",
    options: [
      "boost the HF signal's transmitted power well beyond the levels normally permitted for VHF communication.",
      "physically extend or retract the HF antenna's length in flight to change the aircraft's radar cross-section, a mechanism unrelated to how HF antenna coupling actually works, which instead adjusts electrical tuning components rather than the antenna's physical length to match the selected transmit frequency.",
      "convert the HF radio's voice signal into a digital data link format before transmission.",
      "automatically adjust the electrical characteristics of the aircraft's HF antenna system to match the selected transmit frequency, since an HF antenna's efficiency is highly sensitive to the relationship between its physical length and the wavelength in use.",
    ],
    answer: 3,
    explain:
      "Because an HF antenna's radiating efficiency depends heavily on its electrical length relative to the wavelength of the frequency in use, and aircraft HF antennas are necessarily a fixed physical length, an antenna coupler automatically retunes the antenna system's electrical characteristics (through adjustable inductance and capacitance) each time the crew selects a new HF frequency, matching the antenna to that frequency so the signal can be efficiently radiated.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: HF Communication",
  },
  {
    id: 7,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "A Pilot Report (PIREP), relayed by radio to ATC or a Flight Service Station, is intended primarily to",
    options: [
      "provide other pilots and forecasters with timely, first-hand, in-flight observations -- such as turbulence, icing, cloud tops, or other significant weather actually encountered -- that may not yet be reflected in official forecasts or reports.",
      "report only mechanical or maintenance issues with the aircraft, with no relevance to weather conditions.",
      "formally request a specific altitude or route change from ATC, functioning as a type of clearance request rather than a weather observation.",
      "replace the need for a pilot to file a flight plan before departure, a claim with no basis in the regulations, since a PIREP is an in-flight report of observed conditions and has no bearing whatsoever on the separate requirement to file a flight plan before a flight departs.",
    ],
    answer: 0,
    explain:
      "A PIREP is a first-hand, in-flight observation -- of conditions such as turbulence, icing, cloud tops, visibility, or other significant weather -- relayed by radio to ATC or a Flight Service Station and then disseminated to other pilots and to forecasters, providing real-time information that may not yet be reflected in official forecasts, SIGMETs, or AIRMETs and that can materially improve other crews' situational awareness and decision-making.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Flight Information Services",
  },
  {
    id: 8,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "In the search and rescue alerting system, the sequential phases INCERFA, ALERFA, and DETRESFA reflect",
    options: [
      "three categories of aircraft (light, medium, and heavy) used to determine search and rescue resource allocation, a categorization scheme that does not describe the phases at all, which instead track escalating concern about a specific aircraft's safety rather than sorting aircraft by size or weight class.",
      "an escalating level of concern about an aircraft's safety, progressing from an uncertainty phase, through an alert phase, to a distress phase, each triggering a greater degree of search and rescue response.",
      "three different radio frequencies a pilot in distress must transmit on in sequence, one after another.",
      "three separate transponder codes a pilot must select in sequence during an in-flight emergency.",
    ],
    answer: 1,
    explain:
      "INCERFA (uncertainty phase), ALERFA (alert phase), and DETRESFA (distress phase) represent an escalating sequence of concern in the search and rescue alerting system -- typically triggered by events such as an aircraft failing to report, failing to arrive, or being confirmed to be in difficulty -- with each phase prompting a progressively greater search and rescue response, from initial inquiries up to the activation of a full search and rescue operation.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Search and Rescue",
  },
  {
    id: 9,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "The GPS L1 C/A (Coarse/Acquisition) code, broadcast openly on the L1 frequency, is significant because it",
    options: [
      "is available only to military receivers, with civil GPS receivers instead relying entirely on the encrypted P(Y) code.",
      "provides no usable position information on its own and must always be combined with a ground-based augmentation signal before a receiver can compute a position.",
      "is the basic civil GPS signal most general aviation and many commercial GNSS receivers are built around, unlike the encrypted P(Y) code reserved for authorized (primarily military) users.",
      "was permanently discontinued when Selective Availability was turned off in 2000, and has since been replaced by the L5 frequency for all civil use.",
    ],
    answer: 2,
    explain:
      "The L1 C/A code is the openly broadcast civil GPS signal that the great majority of general aviation and many commercial GNSS receivers are built around, distinct from the encrypted P(Y) code reserved for authorized users, and it remains in service today; newer civil signals such as L2C and L5 supplement, rather than replace, L1 C/A, and none of this is connected to the earlier Selective Availability degradation, which affected signal accuracy rather than which codes were broadcast.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: GNSS",
  },
  {
    id: 10,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "Callsign confusion -- where two aircraft on the same frequency have similar-sounding callsigns -- is a recognized radio communication hazard primarily because",
    options: [
      "it only affects transponder-based surveillance and has no bearing on voice communication.",
      "it causes a total loss of radio reception for both aircraft until one of them changes frequency.",
      "it automatically triggers a TCAS Resolution Advisory between the two aircraft regardless of their actual separation, which describes a distinct and unrelated collision-avoidance function that operates independently of frequency congestion and is not triggered merely because two aircraft happen to be using a similar-sounding callsign on the same frequency.",
      "either aircraft may mistakenly accept, and act on, an ATC instruction actually intended for the other, particularly when workload or radio congestion is high, creating the potential for a clearance to go unactioned by its intended recipient while being wrongly followed by another aircraft.",
    ],
    answer: 3,
    explain:
      "When two aircraft on the same frequency have similar-sounding callsigns, either crew may mistakenly believe an ATC instruction was addressed to them and act on it -- and the aircraft that was actually meant to receive it may never respond -- which is why controllers are trained to watch for and manage similar callsigns (sometimes by using an aircraft's full callsign more often, or coordinating a temporary callsign change) and why pilots are encouraged to listen carefully and query an instruction that does not clearly match their own aircraft.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Radiotelephony Procedures",
  },
  {
    id: 11,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "When asked to give a radio check, a pilot's response using the standard readability scale (in which 5 represents the clearest signal and 1 represents an unreadable one) is understood to describe",
    options: [
      "how clearly and reliably the transmission is being received, rather than the transmitting station's actual signal strength as measured at the source.",
      "the geographic distance, in nautical miles, between the two stations.",
      "the exact signal strength, in watts, being transmitted by the other station.",
      "the number of other aircraft currently also monitoring the same frequency.",
    ],
    answer: 0,
    explain:
      "The standard readability scale used in a radio check response (commonly expressed as a number from 1 to 5, with 5 being perfectly readable and 1 being unreadable) describes how clearly and reliably the receiving station is able to understand the transmission -- factors such as background noise, distorted audio, or intermittent reception are reflected in this rating, which is a subjective assessment of reception quality rather than any objective measurement of the transmitting station's actual radiated power.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Radiotelephony Procedures",
  },
  {
    id: 12,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "A VOR Test Facility (VOT), where available at an aerodrome, allows a pilot to",
    options: [
      "test the aircraft's transponder and TCAS system using the same signal used to verify VOR accuracy.",
      "check the accuracy of the aircraft's own VOR receiver on the ground by tuning the VOT frequency and confirming the indicated radial and course deviation fall within an established tolerance, rather than checking the accuracy of a VOR ground station.",
      "verify DME accuracy only, with no application to VOR receiver testing, a description that has the purpose backwards, since a VOT broadcasts a fixed test radial specifically so pilots can check their own VOR receiver's accuracy, and provides no DME-related test function at all.",
      "remotely recalibrate a distant VOR ground station's transmitted signal from the cockpit.",
    ],
    answer: 1,
    explain:
      "A VOT transmits a test signal, typically simulating the 360-degree radial from every direction, that a pilot can use on the ground to check their own aircraft's VOR receiver for acceptable accuracy -- the indicated bearing (commonly expected to read 360 with a FROM indication, or 180 with a TO indication, within a specified tolerance) confirms the receiver itself is performing correctly, which is a check of the aircraft's equipment rather than of any particular VOR ground station's signal.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: VOR",
  },
  {
    id: 13,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "VOR ground stations are generally equipped with automatic monitoring equipment that",
    options: [
      "automatically adjusts the station's transmitted frequency to match whatever frequency each aircraft's receiver happens to be tuned to.",
      "requires a technician to manually fly a calibration aircraft past the station every time before the signal can be considered valid for that flight.",
      "continuously checks the radiated signal for excessive bearing error or reduced power, and either alerts the responsible facility or automatically shuts down (or switches to a standby transmitter) if the signal falls outside tolerance, helping protect pilots from unknowingly using a faulty signal.",
      "has no ability to detect a degraded signal, relying entirely on pilot reports to identify a faulty VOR station, a description that understates the built-in monitoring most VOR facilities actually carry, which continuously checks the radiated signal itself for excessive bearing error or reduced power rather than waiting on pilot reports alone.",
    ],
    answer: 2,
    explain:
      "VOR ground stations are fitted with automatic monitoring equipment that continuously checks the radiated signal for excessive bearing error, reduced power, or other faults; if the signal falls outside established tolerances, the monitor typically alerts the controlling facility, switches the station to a standby transmitter, or shuts the station down entirely, which is an important safeguard against a pilot unknowingly relying on a faulty or misleading VOR signal.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: VOR",
  },
  {
    id: 14,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "SATCOM voice and data link services relying on geostationary satellites have a recognized coverage limitation in that",
    options: [
      "geostationary SATCOM coverage is limited to equatorial regions only, with no service available anywhere outside the tropics.",
      "geostationary satellites are unusable for aviation communication of any kind and are used only for television and radio broadcasting.",
      "geostationary SATCOM provides uniformly excellent coverage at every latitude, including directly over the poles, with no degradation anywhere on Earth, which overlooks the very low signal elevation angles -- and resulting coverage gaps -- that geostationary satellites produce at high latitudes because of their fixed position above the equator.",
      "geostationary satellites orbit above the equator, so their signal elevation angle becomes very low (or the satellite drops below the horizon entirely) at high latitudes, leaving little or no reliable coverage near the poles -- which is why HF communication remains important for polar routes.",
    ],
    answer: 3,
    explain:
      "Because geostationary satellites are positioned in a fixed orbit above the equator, an aircraft's signal path to one of them becomes an increasingly low elevation angle as the aircraft moves toward higher latitudes, and near the poles the satellite may drop below the usable horizon entirely -- this leaves a coverage gap that geostationary SATCOM cannot fill on polar routes, which is a key reason HF communication (using sky wave propagation rather than a satellite link) remains an important, sometimes mandatory, capability for flights operating over polar regions.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Satellite Communication",
  },
  {
    id: 15,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "A Flight Service Station (FSS) specialist, as distinguished from an air traffic controller, generally",
    options: [
      "provides advisory information -- such as traffic, weather, and airport conditions -- to pilots, particularly at uncontrolled aerodromes and in remote areas, but does not issue binding air traffic control instructions or clearances.",
      "communicates with aircraft exclusively through CPDLC data link, with no voice communication capability.",
      "has identical authority to an air traffic controller and can issue mandatory separation instructions to aircraft in controlled airspace.",
      "is responsible only for aircraft maintenance dispatch decisions, with no role in providing information to pilots in flight.",
    ],
    answer: 0,
    explain:
      "An FSS specialist provides advisory services -- relaying traffic, weather, and aerodrome condition information, and coordinating with pilots, particularly at uncontrolled aerodromes and in remote areas of Canada where no air traffic control unit is present -- but does not have the authority to issue binding air traffic control instructions or separation clearances, which remains the role of a certified air traffic controller operating in controlled airspace.",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Air Traffic Services",
  },
  {
    id: 16,
    subject: "Canada TC ATPL",
    system: "Radio Communications and Aids to Navigation",
    q: "An Aerodrome Traffic Frequency (ATF), as distinguished from a Mandatory Frequency (MF) area, is generally the designated frequency used at an uncontrolled aerodrome where",
    options: [
      "only aircraft equipped with a Mode S transponder are permitted to operate, with all other aircraft excluded.",
      "there is no FSS or control tower actively monitoring and responding on the frequency, so pilots broadcast their intentions and positions for mutual situational awareness among themselves, rather than receiving traffic or advisory information from a ground station as they would in an MF area.",
      "an FSS specialist actively monitors the frequency and is legally required to issue mandatory instructions to every aircraft operating in the vicinity, which describes an MF area's structure rather than an ATF, since no ground station monitors or issues instructions on an ATF, leaving pilots to self-announce for mutual situational awareness instead.",
      "radio communication is entirely prohibited, and all traffic separation must be achieved visually with no broadcasts at all.",
    ],
    answer: 1,
    explain:
      "At an aerodrome using an Aerodrome Traffic Frequency (ATF), there is typically no ground station actively monitoring and responding on the frequency, so pilots self-announce their position and intentions primarily to build mutual situational awareness among each other, rather than receiving traffic and advisory calls from an FSS specialist as they would in a designated Mandatory Frequency (MF) area, where an FSS unit does actively monitor the frequency and provide such information (though, like an ATF, participation on an MF frequency does not constitute air traffic control separation).",
    reference: "TP 690 -- Radio Communications and Aids to Navigation: Aerodrome Communication Procedures",
  },
];
