import type { Question } from "../../../types";

// Canada TC ATPL question bank, Batch 14 -- Section 6: Theory of
// Flight, second pass. Original questions written from aerodynamic
// principles and the TP 690 syllabus (topic headings only, no sample
// questions). Covers drag, lateral/directional stability and
// dynamics, stall characteristics, and high-speed flight topics not
// yet addressed in batch 6. Not transcribed or adapted from any
// commercial test-prep publisher.
export const CANADA_TC_ATPL_BATCH_14_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "On a total drag curve plotted against airspeed, the speed for best lift-to-drag ratio (best L/D) corresponds to",
    options: [
      "the speed at which parasite drag alone is at its minimum, regardless of induced drag.",
      "the speed at which total drag (induced plus parasite drag) is at its minimum.",
      "the aircraft's never-exceed speed (VNE), which is defined specifically as the best L/D speed for that airframe.",
      "the speed at which induced drag alone is at its maximum, since maximum induced drag maximizes lift generated per unit of drag.",
    ],
    answer: 1,
    explain:
      "Induced drag decreases with increasing airspeed while parasite drag increases with it, so the two curves cross at a specific speed where their sum (total drag) is at a minimum -- that speed is, by definition, the best lift-to-drag ratio speed, giving the greatest lift for the least drag and the best glide or maximum-range performance.",
    reference: "TP 690 Section 6 - Theory of Flight, Drag",
  },
  {
    id: 2,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Increasing a wing's aspect ratio (span squared divided by area), while keeping wing area constant, generally",
    options: [
      "increases induced drag for a given amount of lift, since a longer wing always experiences greater total aerodynamic drag.",
      "reduces parasite drag specifically, while leaving induced drag completely unaffected by the change.",
      "reduces induced drag for a given amount of lift, since a longer, narrower wing sheds proportionally weaker wingtip vortices relative to its span.",
      "has no effect on induced drag at all; aspect ratio only affects an aircraft's structural weight.",
    ],
    answer: 2,
    explain:
      "Induced drag is closely tied to how the wing sheds vorticity at its tips relative to its span -- a higher aspect ratio (long, narrow) wing produces weaker wingtip vortices relative to the lift it generates, reducing induced drag, which is why gliders and long-range aircraft favour high-aspect-ratio wings despite the structural weight penalty of a longer span.",
    reference: "TP 690 Section 6 - Theory of Flight, Drag",
  },
  {
    id: 3,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Adverse yaw, which requires rudder input to counteract during a coordinated roll, is caused by",
    options: [
      "the pilot applying too much rudder before the ailerons are deflected, rather than being a property of the ailerons themselves.",
      "the vertical stabilizer producing excess side force whenever the ailerons are deflected, independent of any change in wing lift.",
      "engine torque reaction alone, which is unrelated to aileron deflection and occurs even in wings-level flight.",
      "the down-going aileron on the rising wing producing more lift and more induced drag than the up-going aileron on the descending wing, yawing the nose toward the descending wing.",
    ],
    answer: 3,
    explain:
      "When ailerons are deflected to roll the aircraft, the down-going aileron (on the wing that's rising) increases that wing's lift and, with it, its induced drag -- more than the up-going aileron reduces drag on the other wing. That drag imbalance yaws the nose toward the wing that's descending, opposite to the direction of roll, which is exactly why coordinated rudder input is needed to counter it.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 4,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Dihedral effect, as an aerodynamic property, refers to",
    options: [
      "the tendency to roll away from a sideslip, generated by dihedral, wing sweep, or a high wing position, and is a lateral (roll) stability property distinct from directional (yaw) stability.",
      "the structural strengthening built into a wing's spar to resist the increased bending loads of dihedral, unrelated to aerodynamics.",
      "the geometric angle between the wing chord line and the fuselage reference line, unrelated to any stability characteristic.",
      "the tendency to yaw away from a sideslip, generated exclusively by the vertical stabilizer, and is a directional stability property with no relationship to roll.",
    ],
    answer: 0,
    explain:
      "Dihedral effect is specifically the tendency to roll (not just yaw) away from a sideslip, restoring wings-level flight -- it's a lateral stability property, and it can arise from several design features besides literal dihedral angle, including wing sweep and a high-mounted wing, which is why it's kept conceptually distinct from directional (weathercock) stability provided by the vertical stabilizer.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 5,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Spiral instability (spiral divergence) describes a tendency in which",
    options: [
      "the aircraft pitches up and down in a long-period oscillation around its longitudinal axis with no rolling or yawing component at all.",
      "a small, undisturbed bank angle gradually steepens on its own, developing into a descending spiral if left uncorrected, because directional stability dominates over dihedral effect.",
      "the aircraft returns promptly to wings-level flight without any pilot input whenever a bank angle is introduced, regardless of relative stability strength.",
      "the aircraft oscillates in a combined rolling and yawing motion at a roughly constant frequency, neither growing nor decaying over time.",
    ],
    answer: 1,
    explain:
      "Spiral instability arises when an aircraft's directional (yaw) stability is strong relative to its dihedral (roll) effect: a bank angle causes a slight sideslip, the strong directional stability yaws the nose further into the turn, generating more bank, and the cycle compounds into a slowly steepening, descending spiral rather than a self-correcting return to wings-level.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 6,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Dutch roll is best described as",
    options: [
      "a steady, non-oscillatory sideslip that persists indefinitely once established, with no rolling component.",
      "a one-time, non-oscillatory yaw that occurs only at the moment of engine failure on a multi-engine aircraft.",
      "a coupled, oscillatory combination of yawing and rolling motion, arising from an interaction between directional and lateral stability.",
      "a purely longitudinal, pitch-only oscillation that develops independently of any yaw or roll motion.",
    ],
    answer: 2,
    explain:
      "Dutch roll is a coupled oscillation: as the aircraft yaws one way, dihedral effect rolls it in response, and as it rolls, the resulting sideslip yaws it again, producing a repeating, out-of-phase combination of rolling and yawing motion -- a lateral-directional coupling issue, not a purely pitch (longitudinal) phenomenon, which is why many swept-wing jets fit a yaw damper specifically to suppress it.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 7,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "For a given wing, the critical angle of attack at which the wing stalls is",
    options: [
      "only meaningful for symmetric airfoils; cambered airfoils, by design, have no defined critical angle of attack.",
      "directly proportional to airspeed, meaning a higher airspeed always allows a correspondingly higher AoA before the stall occurs.",
      "dependent entirely on weight, and is unrelated to angle of attack; a heavier aircraft stalls at a fixed indicated airspeed regardless of AoA.",
      "essentially constant regardless of airspeed, weight, or load factor; the wing stalls at that AoA whether flown slowly and lightly loaded or fast and heavily loaded (as in a steep turn).",
    ],
    answer: 3,
    explain:
      "The stall is fundamentally an angle-of-attack phenomenon, not an airspeed phenomenon: a given wing separates airflow and stalls at essentially the same critical AoA regardless of airspeed, weight, or load factor -- which is exactly why an aircraft can stall at a much higher indicated airspeed in a steep, high-load-factor turn than it does in level flight, even though the AoA at the moment of stall is the same in both cases.",
    reference: "TP 690 Section 6 - Theory of Flight, Stalls",
  },
  {
    id: 8,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "On a conventional (non-supercritical) airfoil, as angle of attack is increased toward the stall, the center of pressure generally",
    options: [
      "moves forward, which is part of why an approaching stall tends to increase (rather than decrease) any existing nose-up pitching tendency.",
      "moves aft, which reduces any nose-up pitching tendency as the stall is approached.",
      "moves outward along the span toward the wingtip, rather than moving fore or aft along the chord at all.",
      "remains fixed at exactly 25% of the mean aerodynamic chord at all angles of attack up to and including the stall.",
    ],
    answer: 0,
    explain:
      "As angle of attack rises toward the critical angle on a conventional airfoil, the center of pressure migrates forward along the chord -- shifting the aerodynamic force further ahead of the wing's reference point and tending to increase any nose-up pitching moment already present, part of the aerodynamic picture pilots need to understand when approaching a stall.",
    reference: "TP 690 Section 6 - Theory of Flight, Stalls",
  },
  {
    id: 9,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Wing twist built in so that the wingtip has a lower angle of incidence than the wing root -- commonly called washout -- is used primarily to",
    options: [
      "increase the wing's critical Mach number by reducing the local angle of attack near the wingtip at high speed.",
      "ensure the wing root stalls before the wingtip, preserving aileron effectiveness and providing a more gradual, controllable stall onset.",
      "reduce structural bending loads at the wing root during a hard landing, unrelated to stall behaviour.",
      "increase induced drag deliberately, as a designed-in speed brake effect during the landing flare.",
    ],
    answer: 1,
    explain:
      "By giving the wingtip a lower angle of incidence than the root, washout ensures the root reaches its critical angle of attack -- and starts to stall -- before the tip does. That keeps the ailerons, out near the tips, flying in attached airflow longer, preserving roll control and giving a more gradual, controllable stall onset rather than an abrupt, wingtip-first departure.",
    reference: "TP 690 Section 6 - Theory of Flight, Stalls",
  },
  {
    id: 10,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "For a wing of a given span and area, an elliptical spanwise lift distribution is theoretically significant because it",
    options: [
      "is required by certification standards for all transport-category aircraft, with no other lift distribution permitted.",
      "eliminates parasite drag entirely, regardless of the wing's surface finish or frontal area.",
      "produces the minimum possible induced drag for that span and area, making it the aerodynamic benchmark other planform shapes are compared against.",
      "guarantees the wingtip stalls before the wing root, regardless of any washout built into the wing.",
    ],
    answer: 2,
    explain:
      "An elliptical lift distribution is the theoretical minimum-induced-drag case for a given span and wing area -- real wings (tapered, swept, or rectangular) are compared against it as a benchmark, and designers often taper a wing's planform specifically to approximate an elliptical distribution and capture some of that induced-drag benefit without the manufacturing cost of building a true elliptical wing.",
    reference: "TP 690 Section 6 - Theory of Flight, Drag",
  },
  {
    id: 11,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Comparing two aircraft of similar size and wing area, one with substantially higher wing loading (weight divided by wing area) will generally exhibit",
    options: [
      "a higher stall speed and a rougher ride in turbulence, since both effects move in the same direction.",
      "no difference in stall speed or turbulence response; wing loading affects only cruise fuel efficiency.",
      "a lower stall speed and a rougher ride in turbulence, the opposite of the typical relationship.",
      "a higher stall speed and a smoother ride in turbulence, since the higher wing loading resists gust-induced accelerations more effectively per unit of wing area.",
    ],
    answer: 3,
    explain:
      "Higher wing loading means each unit of wing area is supporting more weight, which pushes stall speed up (more lift is needed per unit area to support the same total weight) but also makes the aircraft comparatively less responsive to a given gust -- a heavier load per unit of wing area is less easily accelerated by the same turbulent disturbance, giving a smoother ride, a trade-off pilots transitioning between light and heavy aircraft types need to anticipate.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 12,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "An aircraft designed with relaxed static stability (an inherently, only marginally, or slightly negatively stable airframe) relies on",
    options: [
      "a flight control computer that continuously and automatically commands control surface deflections to provide artificial stability the airframe itself does not fully provide.",
      "the pilot manually and continuously correcting small deviations, since no automated system can substitute for natural aerodynamic stability.",
      "a larger horizontal stabilizer than a conventionally stable design of the same size would require.",
      "increased dihedral angle alone to restore the static stability margin the design would otherwise lack.",
    ],
    answer: 0,
    explain:
      "Relaxed static stability trades away some or all of an airframe's natural, aerodynamic self-correcting tendency -- typically to reduce trim drag and improve maneuverability or fuel efficiency -- and makes up for it with a fly-by-wire flight control computer that senses deviations and commands corrective control surface movements automatically, far faster and more continuously than a pilot could manage by hand.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 13,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "Longitudinal (pitch) dynamic stability is often described in terms of two distinct oscillatory modes: a short-period oscillation and a phugoid. These two modes differ mainly in that",
    options: [
      "the short-period oscillation involves only roll and yaw, while the phugoid involves only pitch, with no overlap between the two axes at all.",
      "the short-period oscillation is rapid and normally well damped, while the phugoid is a slow, long-period exchange between airspeed and altitude that can persist with comparatively little damping.",
      "both modes have identical periods and damping characteristics, and the distinction is purely a matter of naming convention.",
      "the phugoid occurs only at supersonic speeds, while the short-period oscillation occurs only in subsonic flight.",
    ],
    answer: 1,
    explain:
      "The short-period mode is a quick pitch oscillation, typically over in a few seconds and well damped in most transport aircraft. The phugoid is a much slower, longer-period motion -- essentially a gentle trade-off between airspeed and altitude at roughly constant angle of attack -- that can take a minute or more per cycle and is often only lightly damped, which is why pilots are trained to recognize and not over-control it.",
    reference: "TP 690 Section 6 - Theory of Flight, Stability and Control",
  },
  {
    id: 14,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "The 'area rule,' applied to some high-speed aircraft designs (often visible as a fuselage that narrows, or 'waists,' where the wings join it), is intended to",
    options: [
      "increase the fuselage's internal volume for cargo or fuel, with no relationship to aerodynamic drag at any speed.",
      "reduce induced drag specifically, having no effect on wave drag or transonic performance.",
      "smooth the aircraft's total cross-sectional area distribution along its length, reducing transonic wave drag compared to an unmodified fuselage of constant cross-section.",
      "improve low-speed stall characteristics, with its transonic drag effects considered a secondary and unintended benefit.",
    ],
    answer: 2,
    explain:
      "Wave drag near and above the critical Mach number is sensitive to how abruptly an aircraft's total cross-sectional area changes along its length. By narrowing the fuselage where the wings add their own cross-sectional area, the area-rule shape keeps the overall area distribution smoother, reducing transonic wave drag compared to a fuselage that stayed a constant cross-section through the wing root.",
    reference: "TP 690 Section 6 - Theory of Flight, High-Speed Flight",
  },
  {
    id: 15,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "A T-tail configuration is particularly associated with the risk of a 'deep stall' because, at a high angle of attack,",
    options: [
      "the vertical fin itself stalls first, before the wing reaches its own critical angle of attack, initiating an uncommanded yaw.",
      "a T-tail always increases the aircraft's stall speed compared to an identical airframe with a conventional low tail.",
      "the horizontal stabilizer is mounted so low that ground effect interferes with elevator authority during the stall recovery.",
      "the horizontal stabilizer, mounted high on the vertical fin, can become blanketed by turbulent, separated wake flow from the stalled wing, reducing or eliminating its pitch-control (and pitch-down recovery) authority.",
    ],
    answer: 3,
    explain:
      "With the horizontal stabilizer mounted at the top of the fin, a T-tail sits directly in the turbulent, separated wake shed by a deeply stalled wing at high angle of attack. That blanketing can degrade or even eliminate the elevator's normal nose-down recovery authority right when it's needed most -- the specific mechanism behind the T-tail 'deep stall' or 'locked-in stall' hazard that certification requirements and pilot training specifically address.",
    reference: "TP 690 Section 6 - Theory of Flight, Stalls",
  },
  {
    id: 16,
    subject: "Canada TC ATPL",
    system: "Theory of Flight",
    q: "At high altitude, the narrowing gap between the low-speed (stall) buffet boundary and the high-speed (Mach) buffet boundary -- sometimes called the 'coffin corner' -- occurs because",
    options: [
      "as altitude increases, the indicated airspeed for stall stays roughly constant for a given weight, while the indicated airspeed at which Mach buffet begins decreases, narrowing the usable speed range between the two.",
      "the coffin corner refers to a fixed indicated airspeed that occurs at exactly the same altitude for every aircraft type, regardless of weight or design.",
      "as altitude increases, the stall buffet boundary disappears entirely, leaving only the Mach buffet boundary as a limit.",
      "as altitude increases, both the stall buffet speed and the Mach buffet speed increase at the same rate, so the margin between them stays constant everywhere.",
    ],
    answer: 0,
    explain:
      "For a given weight, the indicated stall speed stays roughly the same regardless of altitude, but true airspeed (and with it, Mach number) for any given indicated airspeed rises with altitude -- so the indicated airspeed at which Mach buffet begins actually decreases as altitude increases. At high enough altitude the two boundaries converge toward the same narrow band of indicated airspeed, squeezing the safe operating margin -- the classic 'coffin corner' picture.",
    reference: "TP 690 Section 6 - Theory of Flight, High-Speed Flight",
  },
];
