import type { Question } from "../../../types";

// ATPL General Knowledge - Airframe & Structures (plus a few landing gear
// items). Original questions written from general, widely-published
// aircraft structures/landing gear knowledge, not copied verbatim from any
// single source. No company, brand, or publisher names appear below.
export const AIRFRAME_STRUCTURES_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "ATPL General Knowledge",
    system: "Airframe & Structures",
    q: "Duralumin, a traditional aircraft structural alloy based on aluminium with copper as its main additional constituent, is generally:",
    options: [
      "Hard to weld by conventional fusion welding, but with good thermal conductivity",
      "Easy to weld, but with poor thermal conductivity",
      "Hard to weld, with poor thermal conductivity",
      "Easy to weld, with good thermal conductivity",
    ],
    answer: 0,
    explain:
      "Duralumin is an aluminium/copper-based alloy with good strength and reasonably good thermal conductivity, but like many aluminium alloys it is comparatively hard to weld by conventional fusion welding - one reason riveted rather than welded construction has traditionally been favoured for aluminium airframes.",
    reference: "Airframe & Structures - Aircraft Alloys",
  },
  {
    id: 2,
    subject: "ATPL General Knowledge",
    system: "Airframe & Structures",
    q: "In a stressed-skin wing structure, bending loads are primarily carried by:",
    options: [
      "The spars together with the skin itself",
      "The stringers together with the spars",
      "The ribs together with the stringers",
      "The skin alone, independent of the spars",
    ],
    answer: 0,
    explain:
      "In a stressed-skin design, the wing skin is a fully load-bearing structural member, not just an aerodynamic covering. Bending loads are shared between the spars, which run span-wise and are the primary bending members, and the skin itself, which is stressed to carry a meaningful share of the load.",
    reference: "Airframe & Structures - Stressed Skin Construction",
  },
  {
    id: 3,
    subject: "ATPL General Knowledge",
    system: "Airframe & Structures",
    q: "In an older, non-stressed-skin wing structure, where the skin is not a primary load-bearing member, bending loads are primarily carried by:",
    options: [
      "The spars alone",
      "The ribs alone",
      "The skin alone",
      "The spars together with the skin",
    ],
    answer: 0,
    explain:
      "In a non-stressed-skin design, the skin contributes essentially nothing to carrying bending loads. That job falls entirely to the internal spar structure, with the skin serving mainly to maintain aerodynamic shape and, together with ribs, to transmit local aerodynamic pressure loads into the structure.",
    reference: "Airframe & Structures - Non-Stressed Skin Construction",
  },
  {
    id: 4,
    subject: "ATPL General Knowledge",
    system: "Airframe & Structures",
    q: "In fuselage construction, one function of stringers, the longitudinal stiffening members running along the fuselage, is to:",
    options: [
      "Support the skin and help carry some of the cabin pressurization loads as tensile stress",
      "Provide an attachment point for cabin insulation only",
      "Provide an alternate load path solely in the event a frame fails",
      "Primarily resist shear stress rather than tension",
    ],
    answer: 0,
    explain:
      "Stringers run lengthwise between the fuselage's circumferential frames, stiffening and supporting the skin against buckling and helping the skin share the tensile stresses generated by cabin pressurization, in addition to carrying bending loads along the fuselage length.",
    reference: "Airframe & Structures - Fuselage Stringers",
  },
  {
    id: 5,
    subject: "ATPL General Knowledge",
    system: "Airframe & Structures",
    q: "An aircraft designed and certified primarily for long-haul operations is generally not well suited to a short-haul role, largely because:",
    options: [
      "Its structure is given a fatigue life based on its intended usage pattern, and short-haul flying accumulates pressurization and landing cycles much faster relative to flight hours",
      "Checklists would take too long to complete on a short flight",
      "Its fuel tanks would remain empty for most of a short flight, straining the structure",
      "It would simply use too much fuel on short sectors, with no structural implication",
    ],
    answer: 0,
    explain:
      "Airframe fatigue life is calculated against an assumed usage pattern - a long-haul design's fatigue life is typically expressed in flight hours, based on relatively few but long flights. Flown short-haul instead, the aircraft accumulates the cyclic loading of pressurization and landing gear cycles far more often per flight hour than intended, which can use up its structural fatigue life much faster than its hours alone would suggest.",
    reference: "Airframe & Structures - Structural Fatigue Life",
  },
  {
    id: 6,
    subject: "ATPL General Knowledge",
    system: "Landing Gear",
    q: "The purpose of the torque links (torque arms) fitted to an oleo-pneumatic landing gear leg is to:",
    options: [
      "Prevent the lower, sliding part of the gear leg from rotating relative to the fixed upper cylinder",
      "Transfer braking torque from the wheel to the axle",
      "Position the wheels correctly just before touchdown",
      "Prevent shimmy of the nose wheel specifically",
    ],
    answer: 0,
    explain:
      "Torque links connect the lower sliding piston of an oleo-pneumatic gear leg to its fixed upper cylinder, allowing the leg to compress and extend freely while preventing the lower part - and the wheel/axle it carries - from rotating around the leg's axis, keeping the wheel correctly aligned.",
    reference: "Landing Gear - Torque Links",
  },
  {
    id: 7,
    subject: "ATPL General Knowledge",
    system: "Landing Gear",
    q: "During full dynamic (aquaplaning) hydroplaning, the effective coefficient of friction between tyre and runway is generally close to:",
    options: [
      "0.0",
      "0.5",
      "0.1",
      "1.0",
    ],
    answer: 0,
    explain:
      "In full dynamic hydroplaning, a wedge of water lifts the tyre completely clear of the runway surface, leaving essentially no direct tyre-to-runway contact to generate friction. Braking and directional control become almost entirely ineffective, which is why hydroplaning is treated as such a serious hazard on a wet or contaminated runway.",
    reference: "Landing Gear - Hydroplaning",
  },
  {
    id: 8,
    subject: "ATPL General Knowledge",
    system: "Landing Gear",
    q: "An underinflated tyre operated on a dry runway tends to:",
    options: [
      "Increase wear on the tyre's shoulders (the outer edges of the tread)",
      "Increase wear concentrated on the tyre's crown (centre of the tread)",
      "Reduce the tyre's operating temperature",
      "Increase the tyre's hydroplaning speed",
    ],
    answer: 0,
    explain:
      "An underinflated tyre bulges more at the sidewalls under load, causing the tread's outer shoulders to bear a disproportionate share of the contact-patch load and wear faster than the centre - the opposite of the crown wear characteristic of an overinflated tyre. Under-inflation also raises tyre operating temperature and reduces, rather than increases, the speed at which some forms of hydroplaning occur.",
    reference: "Landing Gear - Tyre Inflation and Wear",
  },
  {
    id: 9,
    subject: "ATPL General Knowledge",
    system: "Landing Gear",
    q: "A landing gear leg is considered truly 'locked' in the down position when:",
    options: [
      "It is mechanically secured by an over-centre locking mechanism, independent of hydraulic pressure",
      "The gear-down indicator light is illuminated",
      "The actuating cylinder has simply reached the end of its travel",
      "It has physically reached the fully extended position",
    ],
    answer: 0,
    explain:
      "True mechanical locking relies on an over-centre linkage (a down-lock) that holds the gear extended by its own geometry, not by sustained hydraulic pressure - this is what keeps the gear safely down even if hydraulic pressure is later lost. An indicator light, a cylinder reaching its travel limit, or the leg simply reaching the down position are each just indications or contributing steps, not the locking mechanism itself.",
    reference: "Landing Gear - Down-Lock Mechanism",
  },
];
