import type { Question } from "../../../types";

// ATPL General Knowledge - Electrics. Original questions written from
// general, widely-published aircraft electrical systems knowledge, not
// copied verbatim from any single source. No company, brand, or publisher
// names appear anywhere below.
export const ELECTRICS_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "The primary AC electrical power generated by modern transport aircraft engine-driven generators is typically:",
    options: [
      "400 Hz AC",
      "60 Hz AC",
      "115 Hz DC",
      "60 Hz DC",
    ],
    answer: 0,
    explain:
      "Most transport-category aircraft generate their primary AC power at 400 Hz rather than the 50/60 Hz used in mains power ashore. The higher frequency allows electrical components such as transformers and motors to be built smaller and lighter for a given power rating, which is a significant weight advantage in an airframe.",
    reference: "Electrical - AC Generation Frequency",
  },
  {
    id: 2,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "In an aircraft AC electrical distribution system, the purpose of a Generator Control Breaker (GCB) is to:",
    options: [
      "Connect a generator's output to its own load busbar, and disconnect it when required",
      "Connect the load busbar directly to the synchronizing busbar",
      "Maintain constant generator output frequency regardless of engine speed",
      "Control generator field excitation current",
    ],
    answer: 0,
    explain:
      "The GCB sits between an individual generator and its associated load busbar, connecting the generator's output to the busbar it feeds under normal conditions, and disconnecting it if the generator or its feeder develops a fault - a separate bus tie breaker, not the GCB itself, handles connecting busbars together.",
    reference: "Electrical - Generator Control Breaker",
  },
  {
    id: 3,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "A commonly used AC electrical distribution frequency on transport aircraft is:",
    options: [
      "400 Hz",
      "50 Hz",
      "100 Hz",
      "200 Hz",
    ],
    answer: 0,
    explain:
      "400 Hz is the standard AC frequency used throughout most transport aircraft electrical systems, well above the 50/60 Hz used in ground mains power, chosen primarily to reduce the size and weight of onboard transformers, motors, and generators for a given power output.",
    reference: "Electrical - AC Generation Frequency",
  },
  {
    id: 4,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "On an aircraft whose primary electrical power is DC, an AC supply for certain instruments or systems is typically obtained from:",
    options: [
      "An inverter, which converts DC to AC",
      "A rectifier, which converts DC to AC",
      "A Transformer Rectifier Unit (TRU)",
      "A Constant Speed Drive Unit (CSDU) alone",
    ],
    answer: 0,
    explain:
      "An inverter is the device that converts DC electrical power into AC power - the opposite conversion to a rectifier (AC to DC). On a primarily-DC aircraft, an inverter supplies AC to any systems, such as certain gyroscopic instruments, that specifically require an AC input.",
    reference: "Electrical - DC to AC Conversion",
  },
  {
    id: 5,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "Power supplied for windshield electrical anti-icing/heating on a transport aircraft is typically:",
    options: [
      "Three-phase AC power",
      "115 volts DC",
      "28 volts DC",
      "Single-phase AC power only",
    ],
    answer: 0,
    explain:
      "Windshield heating elements are generally supplied with three-phase AC power, which allows a substantial heating load to be delivered efficiently and evenly, with dedicated controllers regulating the current to maintain the windshield within its designed temperature range and prevent overheating.",
    reference: "Electrical - Windshield Heating Power",
  },
  {
    id: 6,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "'Load shedding' in an aircraft electrical system refers to:",
    options: [
      "An overall, deliberate reduction of electrical loads on the system, typically following a generation source failure",
      "Transferring loads between generators to balance them evenly",
      "Deliberately increasing circuit resistance to limit current",
      "Reducing the supply voltage to non-essential busbars",
    ],
    answer: 0,
    explain:
      "Load shedding is the automatic (or manually commanded) disconnection of non-essential electrical loads - typically galley power, some cabin systems, or other non-critical equipment - to reduce total demand when generation capacity has been reduced, such as after losing a generator, so that remaining essential systems stay adequately powered.",
    reference: "Electrical - Load Shedding",
  },
  {
    id: 7,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "If an aircraft loses all AC generator sources in flight, with only the battery remaining, the essential AC busbar will typically be:",
    options: [
      "Powered from the battery via a static inverter, to keep essential AC-dependent equipment running",
      "Powered directly by the battery with no conversion, since the essential bus can accept DC or AC interchangeably",
      "Lost entirely, since no AC source remains available",
      "Self-powered independently, without drawing from the battery at all",
    ],
    answer: 0,
    explain:
      "With all generators lost, the battery becomes the last electrical source; because the battery only supplies DC, a static inverter converts a portion of that battery power into AC specifically to keep the essential AC busbar - and the AC-dependent instruments and systems on it - powered for as long as the battery lasts.",
    reference: "Electrical - Essential Bus Emergency Power",
  },
  {
    id: 8,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "A 'hot busbar' in an aircraft electrical system is one that:",
    options: [
      "Is permanently connected to the battery, live even with everything else electrically shut down",
      "Is connected to the battery only in an emergency, otherwise isolated",
      "Carries all of the aircraft's non-essential loads",
      "Exclusively supplies galley power",
    ],
    answer: 0,
    explain:
      "A hot battery busbar remains permanently connected directly to the battery, independent of the aircraft's main electrical switching, so a small number of critical items (such as certain fire protection or emergency lighting circuits) stay powered even with the aircraft's main electrical system completely shut down.",
    reference: "Electrical - Hot Battery Busbar",
  },
  {
    id: 9,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "The purpose of a Transformer Rectifier Unit (TRU) in an aircraft electrical system is to:",
    options: [
      "Convert AC power into DC power, typically at a different (usually lower) voltage",
      "Convert DC power into AC power at a higher voltage",
      "Isolate the DC systems powered by generators from the AC systems powered by batteries",
      "Isolate the AC systems powered by generators from the DC systems powered by batteries",
    ],
    answer: 0,
    explain:
      "A TRU takes the aircraft's primary AC supply and both transforms its voltage and rectifies it to DC, providing a DC supply (commonly around 28V) for DC busbars, DC-powered equipment, and battery charging, without needing a separate DC generation source.",
    reference: "Electrical - Transformer Rectifier Unit",
  },
  {
    id: 10,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "A static inverter fitted to a modern aircraft's electrical system is a unit that converts:",
    options: [
      "24V DC electrical power to 115V AC",
      "115V DC electrical power to 24V DC",
      "115V AC electrical power to 24V DC",
      "24V AC electrical power to 24V DC",
    ],
    answer: 0,
    explain:
      "A static inverter converts low-voltage DC (typically around 24 or 28V, as supplied by the battery) into the standard 115V AC used to power essential AC-dependent equipment, providing an AC supply even when no generator is available, such as during total AC generation loss.",
    reference: "Electrical - Static Inverters",
  },
  {
    id: 11,
    subject: "ATPL General Knowledge",
    system: "Electrical",
    q: "Fuel tank booster pumps on a modern jet airliner are typically powered by:",
    options: [
      "Three-phase AC power",
      "Single-phase AC power",
      "28 volts DC supplied via an inverter",
      "12 volts DC directly from the battery",
    ],
    answer: 0,
    explain:
      "Fuel booster pumps are generally driven by three-phase AC induction motors, which give reliable, brushless operation appropriate for a pump that must run continuously and often submerged in fuel, drawing power from the aircraft's standard three-phase AC distribution system.",
    reference: "Electrical - Fuel Pump Power Supply",
  },
];
