import type { Question } from "../../../types";

// ATPL General Knowledge - Fuel Systems. Original questions written from
// general, widely-published aircraft fuel systems knowledge, not copied
// verbatim from any single source. No company, brand, or publisher names
// appear anywhere below.
export const ATPL_FUEL_QUESTIONS: Question[] = [
  {
    id: 1,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "Fuel tank booster pumps, which feed fuel from the tanks toward the engines at low pressure, are typically:",
    options: [
      "Centrifugal pumps, operating at relatively low pressure",
      "Centrifugal pumps, operating at relatively high pressure",
      "Spur gear pumps, operating at relatively high pressure",
      "Spur gear pumps, operating at relatively low pressure",
    ],
    answer: 0,
    explain:
      "Booster pumps are normally centrifugal pumps, chosen because they can run safely even with some vapor present in the fuel (unlike a positive-displacement gear pump), operating at a comparatively low pressure sufficient to feed the engine-driven pump, which then raises pressure much further for injection.",
    reference: "Fuel - Booster Pumps",
  },
  {
    id: 2,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The purpose of a surge box (surge tank baffle box) inside a fuel tank is to:",
    options: [
      "Prevent fuel from sloshing away from the pump inlet during abnormal aircraft manoeuvres",
      "Ventilate the tank during high-pressure refuelling",
      "Allow fuel to move freely between tanks while refuelling",
      "Collect sediment and contaminants at the bottom of the tank",
    ],
    answer: 0,
    explain:
      "A surge box surrounds the boost pump inlet with a perforated housing that keeps a reserve of fuel around the pump pickup even when the aircraft is pitched, rolled, or manoeuvring abnormally and the bulk of the fuel has sloshed elsewhere in the tank, helping prevent the pump from momentarily running dry.",
    reference: "Fuel - Surge Boxes",
  },
  {
    id: 3,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The fuel cross-feed system, connecting the fuel systems of a multi-engine aircraft, exists mainly to allow:",
    options: [
      "Fuel from any tank to be supplied to any engine",
      "Fuel to be transferred directly between the main fuel tanks",
      "Refuelling from a single bowser when only one is available",
      "The engine to be isolated from the fuel system in the event of an engine fire",
    ],
    answer: 0,
    explain:
      "Cross-feed valves connect the fuel supply lines between engines, so that fuel normally dedicated to one engine's tank can, when the valves are opened, be supplied to a different engine - useful for managing an asymmetric fuel state, such as one tank running low or an engine or pump failure on one side.",
    reference: "Fuel - Cross-Feed System",
  },
  {
    id: 4,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The function of baffles fitted inside a fuel tank is primarily to:",
    options: [
      "Reduce fuel surge/sloshing during aircraft manoeuvring",
      "Prevent fuel from migrating toward the wingtip specifically",
      "Prevent booster pump cavitation directly",
      "Reduce fuel flow rate at high altitude",
    ],
    answer: 0,
    explain:
      "Internal baffles partially subdivide a fuel tank, restricting how freely fuel can slosh back and forth or surge as the aircraft manoeuvres. This helps keep the fuel more evenly distributed within the tank and reduces the dynamic loads that sloshing fuel could otherwise place on the tank structure.",
    reference: "Fuel - Tank Baffles",
  },
  {
    id: 5,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "Modern large aircraft fuel quantity indicating systems commonly measure fuel quantity by mass, working on the principle that:",
    options: [
      "Changes in the fuel's dielectric properties, as tank probes become more or less immersed, change the capacitance the system measures",
      "Changes in fuel level change the electromotive force generated by the probes",
      "Changes in fuel level change the electrical resistivity between the probes",
      "Changes in fuel level change the physical distance between capacitor plates",
    ],
    answer: 0,
    explain:
      "Capacitance-type fuel probes act as capacitors with fuel and air, which have different dielectric constants, filling the space between their plates. As fuel level (and therefore how much of each probe is immersed in fuel versus air) changes, the effective dielectric - and hence the measured capacitance - changes in a way the system can convert into a fuel quantity reading, further compensated for fuel density to give a mass reading.",
    reference: "Fuel - Capacitance Fuel Gauging",
  },
  {
    id: 6,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "A vane-type (or similar mechanical) fuel flowmeter commonly works on the principle of:",
    options: [
      "Measuring the fuel's quantity of motion (momentum) as it passes through the meter",
      "Measuring fuel volume and viscosity together",
      "Measuring fuel pressure and temperature together",
      "Measuring changes in capacitive dielectric, as in a fuel quantity probe",
    ],
    answer: 0,
    explain:
      "A common mechanical fuel flowmeter design uses a rotating vaned element in the fuel stream; the torque needed to spin a second element against a calibrated spring relates directly to the momentum (mass flow rate) of the fuel passing through, giving a reading proportional to fuel mass flow rather than volume alone.",
    reference: "Fuel - Fuel Flowmeters",
  },
  {
    id: 7,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "In a gas turbine engine fuel system, a fuel heater is commonly positioned ahead of the fuel filter primarily to:",
    options: [
      "Prevent water suspended in the fuel from freezing and blocking the filter",
      "Help vaporize the fuel before it reaches the filter",
      "Prevent the bulk fuel itself from waxing at low temperature",
      "Reduce fuel viscosity for the booster pump's benefit",
    ],
    answer: 0,
    explain:
      "Fuel almost always carries some dissolved or suspended water. At the low fuel temperatures encountered at altitude, that water can freeze into ice crystals that would otherwise block the fuel filter; a fuel heater, often using engine oil or bleed air as the heat source, warms the fuel enough to keep any water from freezing out before it reaches the filter.",
    reference: "Fuel - Fuel Heaters",
  },
  {
    id: 8,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The purpose of a refuelling Volumetric Top-Off (VTO) unit is to:",
    options: [
      "Automatically close the fuelling valve for that tank once it reaches full",
      "Keep the feeder box within the tank full of fuel at all times",
      "Close the tank vent system once the tank is full",
      "Close surge check valves in the outboard tanks to keep them full until centre-tank fuel is used",
    ],
    answer: 0,
    explain:
      "A VTO unit senses when its associated tank has reached a preset full level during pressure refuelling and automatically shuts the fuelling valve for that tank, allowing multiple tanks to be filled simultaneously from a single pressure refuelling point without requiring a person to manually stop each one at the right moment.",
    reference: "Fuel - Volumetric Top-Off Units",
  },
  {
    id: 9,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "An aircraft fuel dumping (jettison) system is generally designed to dump fuel down to:",
    options: [
      "A predetermined, safe minimum fuel value, not all the way to zero usable fuel",
      "The absolute unusable fuel quantity",
      "A fixed reserve of a set number of gallons remaining in each tank regardless of aircraft type",
      "Exactly the maximum landing weight figure, regardless of remaining reserves",
    ],
    answer: 0,
    explain:
      "A fuel jettison system is designed to stop automatically once a predetermined safe minimum fuel quantity remains, ensuring the aircraft retains adequate fuel reserves for a safe approach, landing, and any required diversion or go-around, rather than being able to dump fuel down to an unsafe or unusable level.",
    reference: "Fuel - Fuel Jettison System",
  },
  {
    id: 10,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "A fuel jettison (dumping) system is generally required to be fitted on an aircraft where:",
    options: [
      "Its maximum landing mass is significantly lower than its maximum take-off mass",
      "Its maximum take-off mass is 7 500 kg or more, regardless of landing mass",
      "It seats 250 or more passengers, regardless of mass figures",
      "It was manufactured after a specific fixed calendar year",
    ],
    answer: 0,
    explain:
      "The general regulatory logic is that if an aircraft's structural/performance maximum landing mass is significantly below its maximum take-off mass, it may be unable to land safely shortly after takeoff without first reducing weight - so a jettison system is required unless the manufacturer can otherwise demonstrate an acceptable overweight landing capability.",
    reference: "Fuel - Fuel Jettison Requirements",
  },
  {
    id: 11,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The fuel tanks of a modern passenger airliner are normally filled during ground refuelling by:",
    options: [
      "Fuel being pumped in under pressure by the refuelling truck/bowser",
      "Fuel being drawn in by suction from the aircraft's own booster pumps",
      "Gravity feed from an elevated fuelling point",
      "The volumetric top-off (VTO) unit acting as the fuel source itself",
    ],
    answer: 0,
    explain:
      "Modern transport aircraft are normally refuelled by pressure refuelling: the ground bowser's own pumps push fuel into the aircraft's tanks through one or more single-point connections, with the aircraft's VTO units automatically stopping flow into each tank as it reaches full, rather than relying on the aircraft to draw fuel in itself.",
    reference: "Fuel - Ground Refuelling Method",
  },
  {
    id: 12,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "A twin-engine transport aircraft would normally be refuelled on the ground using:",
    options: [
      "Pressure refuelling through a single-point connection",
      "Open-line (gravity) refuelling into each tank individually",
      "Over-wing refuelling as the standard method",
      "Suction refuelling drawing fuel up from ground level",
    ],
    answer: 0,
    explain:
      "Pressure refuelling through one or more single-point connections is the standard method for modern transport aircraft, letting all tanks be filled simultaneously and relatively quickly under the ground crew's control, with automatic shut-off as each tank reaches its preset full level.",
    reference: "Fuel - Ground Refuelling Method",
  },
  {
    id: 13,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "The function of baffle check valves fitted within a fuel tank's internal structure is primarily to:",
    options: [
      "Prevent fuel from migrating out toward the wingtip during flight",
      "Reduce overall fuel flow rate at high altitude",
      "Prevent surge/sloshing during aircraft manoeuvring",
      "Prevent booster pump cavitation directly",
    ],
    answer: 0,
    explain:
      "Baffle check valves are one-way valves built into the internal rib/baffle structure of a wing fuel tank; they allow fuel to flow inboard toward the pump/collector area but resist it flowing back outboard toward the wingtip, helping keep the usable fuel supply concentrated where the booster pumps can reach it.",
    reference: "Fuel - Baffle Check Valves",
  },
  {
    id: 14,
    subject: "ATPL General Knowledge",
    system: "Fuel",
    q: "In a twin-engine jet's fuel system, the function of a feeder box (or feeder tank) positioned around the boost pump pickups is to:",
    options: [
      "Prevent pump cavitation by maintaining a local reserve of fuel around the pump inlets",
      "Control the amount of fuel remaining during a fuel dumping operation",
      "Feed fuel specifically to the volumetric top-off unit",
      "Equally distribute fuel between tanks during refuelling",
    ],
    answer: 0,
    explain:
      "A feeder box (similar in principle to a surge box) surrounds the boost pump pickups with a small reservoir kept topped up by one-way check valves from the surrounding tank, ensuring the pumps have fuel immediately available even during manoeuvres or unusual attitudes that might otherwise momentarily uncover the pickups.",
    reference: "Fuel - Feeder Box",
  },
];
